In [1]:
from pathpretrain.embed import generate_embeddings
import pandas
import os

In [ ]:
# ! pip install umap-learn pynndescent

### Read images ID of subjects

In [2]:
WSI_info = pandas.read_csv("/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/JiQing/TCGA_model/WSI/wsi_metadata_with_patches_and_embeddings_and_graphs.csv",index_col=0)
WSI_info

,bcr_patient_barcode,age_at_diagnosis,cigarettes_per_day,primary_diagnosis,tissue_or_organ_of_origin,ajcc_pathologic_stage,race,gender,prior_malignancy,vital_status,ajcc_pathologic_t,ajcc_pathologic_n,ajcc_pathologic_m,survival_time,patches_npy,patches_pkl,embeddings,graphs
0,TCGA-2F-A9KO,63.898630,3.780822,Transitional cell carcinoma,Posterior wall of bladder,Stage IV,white,male,no,1,T3,N1,M0,734.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
1,TCGA-2F-A9KP,66.926027,3.397260,Transitional cell carcinoma,Lateral wall of bladder,Stage IV,white,male,no,1,T3a,N2,MX,364.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
2,TCGA-2F-A9KP,66.926027,3.397260,Transitional cell carcinoma,Lateral wall of bladder,Stage IV,white,male,no,1,T3a,N2,MX,364.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
3,TCGA-2F-A9KQ,69.202740,0.000000,Transitional cell carcinoma,"Bladder, NOS",Stage III,white,male,no,0,T3a,N0,M0,2886.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
4,TCGA-2F-A9KR,59.857534,1.232877,Papillary transitional cell carcinoma,"Bladder, NOS",Stage III,not reported,female,no,1,T3a,N0,M0,3183.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,TCGA-ZF-AA54,71.583562,0.000000,Transitional cell carcinoma,Lateral wall of bladder,Stage III,white,male,no,1,T3,NX,MX,590.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
452,TCGA-ZF-AA58,61.778082,2.136986,Transitional cell carcinoma,"Bladder, NOS",Stage IV,white,female,no,0,T3a,N2,MX,1649.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
453,TCGA-ZF-AA5H,60.608219,0.438356,Transitional cell carcinoma,"Bladder, NOS",Stage IV,white,female,no,0,T3b,N2,M0,897.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
454,TCGA-ZF-AA5N,62.304110,0.547945,Transitional cell carcinoma,"Bladder, NOS",Stage IV,white,female,no,1,T2,NX,M1,168.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
455,TCGA-ZF-AA5P,65.673973,3.397260,Transitional cell carcinoma,Posterior wall of bladder,Stage IV,white,male,no,0,T2b,N2,M0,372.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...

In [3]:
patches_pkl = WSI_info['patches_pkl'].tolist()
patches_pkl = [x for x in patches_pkl if str(x) != 'nan']
print(len(patches_pkl))
patches_pkl

456

['/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KO-01Z-00-DX1.195576CF-B739-4BD9-B15B-4A70AE287D3E.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KP-01Z-00-DX1.3CDF534E-958F-4467-AA7E-FD3C5A86AAAA.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KP-01Z-00-DX2.718C82A3-252B-498E-BFBE-F4E4EB431BF5.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KQ-01Z-00-DX1.1C8CB2DD-5CC6-4E99-A0F9-32A0F598F5F9.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KR-01Z-00-DX1.D6A4BD2D-18F3-4FA6-8272-60392DDAF7B5.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KT-01Z-00-DX2.A06896B2-FC9A-430D-8F59-C89EEA002C8B.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KT-01Z-00-DX1.ADD6D87C-0CC2-4B1F-A75F-108C9EB3970F.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KW-01Z-00-DX1.CECFDA2E-2CE7-4115-B4E6-A3D75B130232.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KW-01Z-00-DX2.10D33B2F-631F-4E3D-BF53-24D40A1088A3.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7M-01Z-00-DX1.05317C75-A8F3-4124-95D2-F039BEFFE63A.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7N-01Z-00-DX1.10AA3499-6678-4DB2-9466-9CB3EA25CBB6.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7Q-01Z-00-DX1.9C30EAED-8DE3-437C-8852-0C64B415AFA8.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7R-01Z-00-DX1.8FBDAFEB-265F-4594-9069-E34BAB417FC4.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7S-01Z-00-DX1.35242781-51FD-4883-A347-6EADC40E39C2.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7W-01Z-00-DX1.9BE6DF4E-480F-483E-8299-D949B5C09B4B.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7Y-01Z-00-DX1.5771D5DA-5163-4F6C-A99A-DA682D3F059F.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA80-01Z-00-DX1.303549D2-42A5-46C4-AD9D-D72337B416E5.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA81-01Z-00-DX1.797432E9-56C6-4142-9AA4-233D7C565BF1.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA82-01Z-00-DX1.D18C9339-88DE-48E7-9D75-1ACB95483F7D.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA83-01Z-00-DX1.432ADCAA-36B5-4F9F-B4AE-6D755805FEF5.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA84-01Z-00-DX1.604B60F3-1E19-4335-9F8D-0D6920B1ACF8.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA86-01Z-00-DX1.C4DC6342-85A3-4F8A-BA6E-B63C554880B4.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA87-01Z-00-DX1.84170458-631E-49C5-9D7F-70126388ADE3.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA89-01Z-00-DX1.6DD89FC0-A062-41F1-AED3-FF8975FAADF3.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-5N-A9KI-01Z-00-DX1.1BAE5EFF-859F-4D0A-8DDC-527E2901F7D4.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-5N-A9KM-01Z-00-DX1.5197F750-D17F-459B-B74D-846F5F50F7B7.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A0C8-01Z-00-DX2.1D788C7B-801F-4957-B1DE-43DCAA82A16A.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A0C8-01Z-00-DX1.E7FC7156-EF0C-4C79-93D1-1345ADB36A45.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13I-01Z-00-DX1.D08284EF-2E42-44FE-A3B9-BEF64076A86E.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13I-01Z-00-DX2.251412B0-EECB-420A-B963-B19432DB3F29.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13J-01Z-00-DX1.F2AFDD81-C88A-45EA-AC10-D9B38E878019.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13J-01Z-00-DX2.289B5C8E-56AF-440D-A844-36BD98B573AF.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A3JM-01Z-00-DX1.33E53972-CEA4-4D84-A5D2-7DAD7B0C27F8.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A5ZZ-01Z-00-DX2.BB151354-01C6-43DE-ABCC-0B03468D54FF.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A5ZZ-01Z-00-DX1.4CF32B22-118E-4570-B341-0F35258329E6.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A0S7-01Z-00-DX1.32588823-EE4E-4F55-B586-29E8E9D98EDE.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A0YX-01Z-00-DX1.B28C49EA-BF1C-44D8-B9A0-DC0A6172702E.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20J-01Z-00-DX1.EB1BC7DB-9BF1-467D-B897-9BA2130320CB.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20N-01Z-00-DX1.0FB9D7FF-BDF5-4768-A6F3-D8D16A899772.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20O-01Z-00-DX1.BD64154E-5CB0-4088-94CC-C48C036E3715.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20P-01Z-00-DX1.721A7D6B-C9F3-4A70-8E84-EA2556349AE1.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20Q-01Z-00-DX1.BFF3D35C-CB0C-49C3-8D35-D5C84E133B49.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20R-01Z-00-DX1.38320FC0-F1E5-401B-9336-D77796456B30.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20T-01Z-00-DX1.96460E53-65E0-425F-B079-939D7AA537BE.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20U-01Z-00-DX1.C2FDF7E9-3391-44E8-9E84-C5EA8EB4AB4C.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20W-01Z-00-DX1.26F73765-704B-4D81-923D-F20860A3EFFC.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A2LA-01Z-00-DX1.B76379CE-99AB-4598-B55B-0FA800B8DB74.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A2LB-01Z-00-DX1.046294E0-4665-41B8-9B95-1A166163EC99.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A2LD-01Z-00-DX1.A2AEDD2E-481A-401B-BDD7-5D680B5E36E9.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A3PH-01Z-00-DX1.18FB196C-9F66-4676-81DC-F58A0A5577D8.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A3PJ-01Z-00-DX1.C730AD35-81DF-4758-97B5-1E9F58E67A2B.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A3PK-01Z-00-DX1.0C10EB75-B766-47DB-8BD0-853F81074355.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42B-01Z-00-DX1.00FCBDE2-728B-4024-A515-64A366DAB307.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42C-01Z-00-DX1.49949E15-B218-4E43-947C-5D73B87B1CA9.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42E-01Z-00-DX1.7DAF02FF-70D0-412D-8EE3-03AC04E83300.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42F-01Z-00-DX1.B934B6A1-C16E-4796-A297-9E92DD74763F.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0EZ-01Z-00-DX1.993A12F0-9687-4E56-B887-13C9453A7E63.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F0-01Z-00-DX1.8EBBC2EF-DA6F-4901-838D-C1AC80E83E92.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F1-01Z-00-DX1.C29436CC-B584-4898-8168-97B5552B1B24.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F6-01Z-00-DX1.05FAB26A-4BE9-42B4-95F0-6BD15EBE8792.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F7-01Z-00-DX1.606C3AFA-F93D-4226-AA49-41B5916F9018.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A1HR-01Z-00-DX1.C56E4296-EB85-4DBA-B0A0-9D6FA097A74F.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A1HS-01Z-00-DX1.CA67D874-12C9-49AB-ACA1-92C202E27083.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A27C-01Z-00-DX1.0FDBC44E-EC0D-4C6F-8B77-177CB1516CF1.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MF-01Z-00-DX1.91768C26-5BB1-4DE6-9737-AA26BD687A75.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MG-01Z-00-DX1.49D55C73-735B-496E-82DA-1F6BFE88D607.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MH-01Z-00-DX1.4A6F7BDC-B7D2-4203-AA8E-7BA5DB8BF3AC.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MI-01Z-00-DX1.5619CA1A-F772-44CC-BBE2-F2C365E2699D.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47S-01Z-00-DX1.1397F7C0-1098-4C42-B158-28A37723F5F6.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47T-01Z-00-DX1.2AFA4BB3-B97C-4C0D-86F4-53A5F3317129.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47V-01Z-00-DX1.DCDFBB74-48BC-434A-ABD3-55367C56F2FD.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47W-01Z-00-DX1.D14F1F9A-E684-4140-9714-3197A4325568.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47X-01Z-00-DX1.1FA2C95C-CFB9-47AA-9BA8-2C2D391BA5D7.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47Y-01Z-00-DX1.1D4B8964-E7AB-4C6F-80AC-AF84B80B80C2.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A5U8-01Z-00-DX1.D0385BD3-3128-41C6-889D-4EC916B2B228.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A5UA-01Z-00-DX1.7352D4EB-46F5-4EAA-95B9-1D869E8291C3.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A7I0-01Z-00-DX1.9920A024-B523-4CB6-992F-0BD80D9E11C9.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A8HX-01Z-00-DX1.92B22756-3D98-4DE6-A077-36C9F1AF1EC2.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A8HY-01Z-00-DX1.53F599FE-3A6D-4BAC-92B2-CBE3F183BB71.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FF-01Z-00-DX1.69267287-0015-4BC2-A965-CEE9D0CFC5AA.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FH-01Z-00-DX1.26AACDC9-1C0B-4AD4-A484-E093515F42B1.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FL-01Z-00-DX1.711B523B-E033-41ED-AE06-6233C89DCC57.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FM-01Z-00-DX1.F9379708-8E04-435E-BF12-8E3222AE728D.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A0YN-01Z-00-DX1.6C5EAAAF-8F14-49D3-8FFC-9BDAE56CAFD0.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A0YO-01Z-00-DX1.847097EC-2E17-44BA-9162-6AA298B7CAFD.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A0YR-01Z-00-DX1.B3690B2C-0B90-47D6-8709-D493A74E3F7B.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A3KJ-01Z-00-DX1.5E6E8B80-4059-4625-AED8-D049F4B63FF7.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A3YL-01Z-00-DX1.813C9F59-869C-4B8E-B295-22F67AD83F37.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A5W6-01Z-00-DX1.11155086-4A71-4207-85B9-CAF7B6D3D60D.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A72E-01Z-00-DX1.11B1B313-85DB-460B-9B78-398224F63A04.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A3-01Z-00-DX1.89FB6586-56D1-4EF7-AE4B-66EED29667CD.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A5-01Z-00-DX1.463753DB-C4EA-4973-AF04-4BD0FF39C19D.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A6-01Z-00-DX1.FC604B50-6BA7-488C-A153-7F9610E6E37B.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A7-01Z-00-DX1.57B1442D-8862-447F-98D4-0D52F7B94E62.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AA-01Z-00-DX1.11F015AE-3B8A-4827-93E2-54F8563BE248.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AB-01Z-00-DX1.D6032D7B-43EF-469B-A29D-D6DC41DB46D7.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AC-01Z-00-DX1.6F484315-00FC-4D41-86E2-16200DC61A04.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AD-01Z-00-DX1.1B438E00-C022-4CB8-994D-C4EE8E009F00.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AE-01Z-00-DX1.85F1B791-E0CD-479F-9C2D-E411981E4471.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AF-01Z-00-DX1.E18DE029-27A6-43A6-9E9D-D0225C7D5324.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AG-01Z-00-DX1.1794B149-3C25-4C51-B96F-1EA24BCBBB3C.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2HX-01Z-00-DX1.F5D261DF-5A52-4BF6-B892-89B245809F7B.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I1-01Z-00-DX1.7EBA720C-60F8-4012-95D2-F4B10FB74A18.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I2-01Z-00-DX1.FF39546E-EE64-4287-8CB5-585801A08519.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I4-01Z-00-DX1.2DE79A2D-575E-4D5A-A6E3-89D551A5FA46.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I6-01Z-00-DX1.7BF86D3B-D4F7-47F9-B021-7FD6B673A238.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IK-01Z-00-DX1.2C3A7E93-113C-4321-94B1-7A228E4897F0.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IL-01Z-00-DX1.B3F0006E-CB53-4475-9576-3411C835B25A.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IM-01Z-00-DX1.ED1A8B22-566E-4A95-AF6D-7C9E536BE2B7.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IN-01Z-00-DX1.2AB0F8FC-CC41-4277-A8AF-8AE709D98DA0.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IQ-01Z-00-DX1.D68A6FD8-6E48-4FC1-BAF3-B80D6198EFAE.pkl',
 '/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IS-01Z-00-DX1.31CABE32-36D7-4920-BF5A-9C9D8B54320F.pkl',

#### Get file size

In [4]:
patch_pkl_less_810_byte = []

for i in patches_pkl:
    print(i)
    file_stats = os.stat(i)
    print(f'File Size in Bytes is {file_stats.st_size}')
    if file_stats.st_size <= 810:
        patch_pkl_less_810_byte.append(i)
        
patch_pkl_less_810_byte # Everything larger than 810 byte

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KO-01Z-00-DX1.195576CF-B739-4BD9-B15B-4A70AE287D3E.pkl
File Size in Bytes is 1050896
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KP-01Z-00-DX1.3CDF534E-958F-4467-AA7E-FD3C5A86AAAA.pkl
File Size in Bytes is 1410801
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KP-01Z-00-DX2.718C82A3-252B-498E-BFBE-F4E4EB431BF5.pkl
File Size in Bytes is 1476939
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KQ-01Z-00-DX1.1C8CB2DD-5CC6-4E99-A0F9-32A0F598F5F9.pkl
File Size in Bytes is 807904
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KR-01Z-00-DX1.D6A4BD2D-18F3-4FA6-8272-60392DDAF7B5.pkl
File Size in Bytes is 1646483
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KT-01Z-00-DX2.A06896B2-FC9A-430D-8F59-C89EEA002C8B.pkl
File Size in Bytes is 1816574
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KT-01Z-00-DX1.ADD6D87C-0CC2-4B1F-A75F-108C9EB3970F.pkl
File Size in Bytes is 1662469
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KW-01Z-00-DX1.CECFDA2E-2CE7-4115-B4E6-A3D75B130232.pkl
File Size in Bytes is 1582863
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KW-01Z-00-DX2.10D33B2F-631F-4E3D-BF53-24D40A1088A3.pkl
File Size in Bytes is 802288
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7M-01Z-00-DX1.05317C75-A8F3-4124-95D2-F039BEFFE63A.pkl
File Size in Bytes is 942848
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7N-01Z-00-DX1.10AA3499-6678-4DB2-9466-9CB3EA25CBB6.pkl
File Size in Bytes is 986196
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7Q-01Z-00-DX1.9C30EAED-8DE3-437C-8852-0C64B415AFA8.pkl
File Size in Bytes is 796708
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7R-01Z-00-DX1.8FBDAFEB-265F-4594-9069-E34BAB417FC4.pkl
File Size in Bytes is 617444
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7S-01Z-00-DX1.35242781-51FD-4883-A347-6EADC40E39C2.pkl
File Size in Bytes is 695392
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7W-01Z-00-DX1.9BE6DF4E-480F-483E-8299-D949B5C09B4B.pkl
File Size in Bytes is 933558
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7Y-01Z-00-DX1.5771D5DA-5163-4F6C-A99A-DA682D3F059F.pkl
File Size in Bytes is 702880
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA80-01Z-00-DX1.303549D2-42A5-46C4-AD9D-D72337B416E5.pkl
File Size in Bytes is 1004018
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA81-01Z-00-DX1.797432E9-56C6-4142-9AA4-233D7C565BF1.pkl
File Size in Bytes is 577471
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA82-01Z-00-DX1.D18C9339-88DE-48E7-9D75-1ACB95483F7D.pkl
File Size in Bytes is 947600
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA83-01Z-00-DX1.432ADCAA-36B5-4F9F-B4AE-6D755805FEF5.pkl
File Size in Bytes is 801676
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA84-01Z-00-DX1.604B60F3-1E19-4335-9F8D-0D6920B1ACF8.pkl
File Size in Bytes is 798724
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA86-01Z-00-DX1.C4DC6342-85A3-4F8A-BA6E-B63C554880B4.pkl
File Size in Bytes is 678974
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA87-01Z-00-DX1.84170458-631E-49C5-9D7F-70126388ADE3.pkl
File Size in Bytes is 664860
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA89-01Z-00-DX1.6DD89FC0-A062-41F1-AED3-FF8975FAADF3.pkl
File Size in Bytes is 1043154
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-5N-A9KI-01Z-00-DX1.1BAE5EFF-859F-4D0A-8DDC-527E2901F7D4.pkl
File Size in Bytes is 1347109
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-5N-A9KM-01Z-00-DX1.5197F750-D17F-459B-B74D-846F5F50F7B7.pkl
File Size in Bytes is 425641
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A0C8-01Z-00-DX2.1D788C7B-801F-4957-B1DE-43DCAA82A16A.pkl
File Size in Bytes is 306755
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A0C8-01Z-00-DX1.E7FC7156-EF0C-4C79-93D1-1345ADB36A45.pkl
File Size in Bytes is 319321
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13I-01Z-00-DX1.D08284EF-2E42-44FE-A3B9-BEF64076A86E.pkl
File Size in Bytes is 319213
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13I-01Z-00-DX2.251412B0-EECB-420A-B963-B19432DB3F29.pkl
File Size in Bytes is 143684
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13J-01Z-00-DX1.F2AFDD81-C88A-45EA-AC10-D9B38E878019.pkl
File Size in Bytes is 151714
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13J-01Z-00-DX2.289B5C8E-56AF-440D-A844-36BD98B573AF.pkl
File Size in Bytes is 56187
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A3JM-01Z-00-DX1.33E53972-CEA4-4D84-A5D2-7DAD7B0C27F8.pkl
File Size in Bytes is 66204
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A5ZZ-01Z-00-DX2.BB151354-01C6-43DE-ABCC-0B03468D54FF.pkl
File Size in Bytes is 332031
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A5ZZ-01Z-00-DX1.4CF32B22-118E-4570-B341-0F35258329E6.pkl
File Size in Bytes is 433959
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A0S7-01Z-00-DX1.32588823-EE4E-4F55-B586-29E8E9D98EDE.pkl
File Size in Bytes is 1251807
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A0YX-01Z-00-DX1.B28C49EA-BF1C-44D8-B9A0-DC0A6172702E.pkl
File Size in Bytes is 910696
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20J-01Z-00-DX1.EB1BC7DB-9BF1-467D-B897-9BA2130320CB.pkl
File Size in Bytes is 542727
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20N-01Z-00-DX1.0FB9D7FF-BDF5-4768-A6F3-D8D16A899772.pkl
File Size in Bytes is 808696
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20O-01Z-00-DX1.BD64154E-5CB0-4088-94CC-C48C036E3715.pkl
File Size in Bytes is 735320
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20P-01Z-00-DX1.721A7D6B-C9F3-4A70-8E84-EA2556349AE1.pkl
File Size in Bytes is 712962
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20Q-01Z-00-DX1.BFF3D35C-CB0C-49C3-8D35-D5C84E133B49.pkl

File Size in Bytes is 924306
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20R-01Z-00-DX1.38320FC0-F1E5-401B-9336-D77796456B30.pkl
File Size in Bytes is 669686
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20T-01Z-00-DX1.96460E53-65E0-425F-B079-939D7AA537BE.pkl
File Size in Bytes is 925458
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20U-01Z-00-DX1.C2FDF7E9-3391-44E8-9E84-C5EA8EB4AB4C.pkl
File Size in Bytes is 1299621
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20W-01Z-00-DX1.26F73765-704B-4D81-923D-F20860A3EFFC.pkl
File Size in Bytes is 899246
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A2LA-01Z-00-DX1.B76379CE-99AB-4598-B55B-0FA800B8DB74.pkl
File Size in Bytes is 795700
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A2LB-01Z-00-DX1.046294E0-4665-41B8-9B95-1A166163EC99.pkl
File Size in Bytes is 1044846
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A2LD-01Z-00-DX1.A2AEDD2E-481A-401B-BDD7-5D680B5E36E9.pkl
File Size in Bytes is 777446
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A3PH-01Z-00-DX1.18FB196C-9F66-4676-81DC-F58A0A5577D8.pkl
File Size in Bytes is 453041
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A3PJ-01Z-00-DX1.C730AD35-81DF-4758-97B5-1E9F58E67A2B.pkl
File Size in Bytes is 910804
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A3PK-01Z-00-DX1.0C10EB75-B766-47DB-8BD0-853F81074355.pkl
File Size in Bytes is 1096368
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42B-01Z-00-DX1.00FCBDE2-728B-4024-A515-64A366DAB307.pkl
File Size in Bytes is 828426
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42C-01Z-00-DX1.49949E15-B218-4E43-947C-5D73B87B1CA9.pkl
File Size in Bytes is 601926
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42E-01Z-00-DX1.7DAF02FF-70D0-412D-8EE3-03AC04E83300.pkl
File Size in Bytes is 832172
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42F-01Z-00-DX1.B934B6A1-C16E-4796-A297-9E92DD74763F.pkl
File Size in Bytes is 669830
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0EZ-01Z-00-DX1.993A12F0-9687-4E56-B887-13C9453A7E63.pkl
File Size in Bytes is 599622
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F0-01Z-00-DX1.8EBBC2EF-DA6F-4901-838D-C1AC80E83E92.pkl
File Size in Bytes is 804016
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F1-01Z-00-DX1.C29436CC-B584-4898-8168-97B5552B1B24.pkl
File Size in Bytes is 1187071
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F6-01Z-00-DX1.05FAB26A-4BE9-42B4-95F0-6BD15EBE8792.pkl
File Size in Bytes is 329295
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F7-01Z-00-DX1.606C3AFA-F93D-4226-AA49-41B5916F9018.pkl
File Size in Bytes is 425281
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A1HR-01Z-00-DX1.C56E4296-EB85-4DBA-B0A0-9D6FA097A74F.pkl
File Size in Bytes is 462113
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A1HS-01Z-00-DX1.CA67D874-12C9-49AB-ACA1-92C202E27083.pkl
File Size in Bytes is 470323
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A27C-01Z-00-DX1.0FDBC44E-EC0D-4C6F-8B77-177CB1516CF1.pkl
File Size in Bytes is 378223
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MF-01Z-00-DX1.91768C26-5BB1-4DE6-9737-AA26BD687A75.pkl
File Size in Bytes is 1000310
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MG-01Z-00-DX1.49D55C73-735B-496E-82DA-1F6BFE88D607.pkl
File Size in Bytes is 281013
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MH-01Z-00-DX1.4A6F7BDC-B7D2-4203-AA8E-7BA5DB8BF3AC.pkl
File Size in Bytes is 531961
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MI-01Z-00-DX1.5619CA1A-F772-44CC-BBE2-F2C365E2699D.pkl
File Size in Bytes is 830696
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47S-01Z-00-DX1.1397F7C0-1098-4C42-B158-28A37723F5F6.pkl
File Size in Bytes is 735644
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47T-01Z-00-DX1.2AFA4BB3-B97C-4C0D-86F4-53A5F3317129.pkl
File Size in Bytes is 681494
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47V-01Z-00-DX1.DCDFBB74-48BC-434A-ABD3-55367C56F2FD.pkl
File Size in Bytes is 587776
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47W-01Z-00-DX1.D14F1F9A-E684-4140-9714-3197A4325568.pkl
File Size in Bytes is 594616
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47X-01Z-00-DX1.1FA2C95C-CFB9-47AA-9BA8-2C2D391BA5D7.pkl
File Size in Bytes is 807760
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47Y-01Z-00-DX1.1D4B8964-E7AB-4C6F-80AC-AF84B80B80C2.pkl
File Size in Bytes is 693376
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A5U8-01Z-00-DX1.D0385BD3-3128-41C6-889D-4EC916B2B228.pkl
File Size in Bytes is 530017
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A5UA-01Z-00-DX1.7352D4EB-46F5-4EAA-95B9-1D869E8291C3.pkl
File Size in Bytes is 479143
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A7I0-01Z-00-DX1.9920A024-B523-4CB6-992F-0BD80D9E11C9.pkl
File Size in Bytes is 409043
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A8HX-01Z-00-DX1.92B22756-3D98-4DE6-A077-36C9F1AF1EC2.pkl
File Size in Bytes is 314101
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A8HY-01Z-00-DX1.53F599FE-3A6D-4BAC-92B2-CBE3F183BB71.pkl
File Size in Bytes is 448899
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FF-01Z-00-DX1.69267287-0015-4BC2-A965-CEE9D0CFC5AA.pkl
File Size in Bytes is 251741
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FH-01Z-00-DX1.26AACDC9-1C0B-4AD4-A484-E093515F42B1.pkl
File Size in Bytes is 595194
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FL-01Z-00-DX1.711B523B-E033-41ED-AE06-6233C89DCC57.pkl
File Size in Bytes is 872028
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FM-01Z-00-DX1.F9379708-8E04-435E-BF12-8E3222AE728D.pkl
File Size in Bytes is 890534
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A0YN-01Z-00-DX1.6C5EAAAF-8F14-49D3-8FFC-9BDAE56CAFD0.pkl
File Size in Bytes is 120534
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A0YO-01Z-00-DX1.847097EC-2E17-44BA-9162-6AA298B7CAFD.pkl
File Size in Bytes is 634762
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A0YR-01Z-00-DX1.B3690B2C-0B90-47D6-8709-D493A74E3F7B.pkl
File Size in Bytes is 287853
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A3KJ-01Z-00-DX1.5E6E8B80-4059-4625-AED8-D049F4B63FF7.pkl
File Size in Bytes is 429529
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A3YL-01Z-00-DX1.813C9F59-869C-4B8E-B295-22F67AD83F37.pkl
File Size in Bytes is 767796
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A5W6-01Z-00-DX1.11155086-4A71-4207-85B9-CAF7B6D3D60D.pkl
File Size in Bytes is 387801
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A72E-01Z-00-DX1.11B1B313-85DB-460B-9B78-398224F63A04.pkl
File Size in Bytes is 761352
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A3-01Z-00-DX1.89FB6586-56D1-4EF7-AE4B-66EED29667CD.pkl
File Size in Bytes is 633394
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A5-01Z-00-DX1.463753DB-C4EA-4973-AF04-4BD0FF39C19D.pkl
File Size in Bytes is 822558
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A6-01Z-00-DX1.FC604B50-6BA7-488C-A153-7F9610E6E37B.pkl
File Size in Bytes is 920418
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A7-01Z-00-DX1.57B1442D-8862-447F-98D4-0D52F7B94E62.pkl
File Size in Bytes is 597246
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AA-01Z-00-DX1.11F015AE-3B8A-4827-93E2-54F8563BE248.pkl
File Size in Bytes is 1158692
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AB-01Z-00-DX1.D6032D7B-43EF-469B-A29D-D6DC41DB46D7.pkl
File Size in Bytes is 614780
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AC-01Z-00-DX1.6F484315-00FC-4D41-86E2-16200DC61A04.pkl
File Size in Bytes is 1252815
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AD-01Z-00-DX1.1B438E00-C022-4CB8-994D-C4EE8E009F00.pkl
File Size in Bytes is 720846
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AE-01Z-00-DX1.85F1B791-E0CD-479F-9C2D-E411981E4471.pkl
File Size in Bytes is 718434
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AF-01Z-00-DX1.E18DE029-27A6-43A6-9E9D-D0225C7D5324.pkl
File Size in Bytes is 1301925
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AG-01Z-00-DX1.1794B149-3C25-4C51-B96F-1EA24BCBBB3C.pkl
File Size in Bytes is 1052660
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2HX-01Z-00-DX1.F5D261DF-5A52-4BF6-B892-89B245809F7B.pkl
File Size in Bytes is 758544
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I1-01Z-00-DX1.7EBA720C-60F8-4012-95D2-F4B10FB74A18.pkl
File Size in Bytes is 389961
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I2-01Z-00-DX1.FF39546E-EE64-4287-8CB5-585801A08519.pkl
File Size in Bytes is 962002
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I4-01Z-00-DX1.2DE79A2D-575E-4D5A-A6E3-89D551A5FA46.pkl
File Size in Bytes is 540493
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I6-01Z-00-DX1.7BF86D3B-D4F7-47F9-B021-7FD6B673A238.pkl
File Size in Bytes is 1014280
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IK-01Z-00-DX1.2C3A7E93-113C-4321-94B1-7A228E4897F0.pkl
File Size in Bytes is 617372
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IL-01Z-00-DX1.B3F0006E-CB53-4475-9576-3411C835B25A.pkl
File Size in Bytes is 768012
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IM-01Z-00-DX1.ED1A8B22-566E-4A95-AF6D-7C9E536BE2B7.pkl
File Size in Bytes is 1355427
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IN-01Z-00-DX1.2AB0F8FC-CC41-4277-A8AF-8AE709D98DA0.pkl
File Size in Bytes is 678074
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IQ-01Z-00-DX1.D68A6FD8-6E48-4FC1-BAF3-B80D6198EFAE.pkl
File Size in Bytes is 880092
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IS-01Z-00-DX1.31CABE32-36D7-4920-BF5A-9C9D8B54320F.pkl
File Size in Bytes is 697300
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IT-01Z-00-DX1.819410F8-5E45-484B-8D98-0A3DAB314C6E.pkl
File Size in Bytes is 769956
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IU-01Z-00-DX1.A624F891-20E8-48F6-8FAE-D046F30E257C.pkl
File Size in Bytes is 1193481
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IV-01Z-00-DX1.3E7EDFE4-61F6-4EA8-9A29-D70C2785E408.pkl
File Size in Bytes is 1289827
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3WW-01Z-00-DX1.4C3751B5-BD3E-4902-A092-B5877B67851F.pkl

File Size in Bytes is 927222
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3WX-01Z-00-DX1.02E25F1B-4726-4D9E-BBC0-CF42F548F559.pkl
File Size in Bytes is 428845
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3WY-01Z-00-DX1.B2B8F28A-A9A4-4C6E-8C7F-3008DF2DE498.pkl
File Size in Bytes is 1145442
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3X1-01Z-00-DX1.DE470E1B-1DB4-4985-B11D-ECB02A65CA6C.pkl
File Size in Bytes is 1257207
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3X2-01Z-00-DX1.CB507611-E3AE-43A2-B5F8-EEAE59423E2E.pkl
File Size in Bytes is 861118
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6AV-01Z-00-DX1.FC632EEE-668B-4757-B2FB-139D869812E0.pkl
File Size in Bytes is 905332
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6AW-01Z-00-DX1.C2453A8C-8282-443C-9E76-5B6CAD2FE69B.pkl
File Size in Bytes is 590080
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B0-01Z-00-DX1.83628045-FDD9-4167-879F-7813FDCA7D97.pkl
File Size in Bytes is 838112
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B1-01Z-00-DX1.16F4E625-D690-45CD-B810-9E7F12EF9A90.pkl
File Size in Bytes is 982704
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B2-01Z-00-DX1.23D318D9-A05D-49D5-8C0E-BAA71BC2AFFA.pkl
File Size in Bytes is 894998
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B5-01Z-00-DX1.A1A01D61-DAA3-4172-8D69-FF0456190967.pkl
File Size in Bytes is 974172
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B6-01Z-00-DX1.CD8B2F09-A5BA-4795-92FD-03A7315C3A2D.pkl
File Size in Bytes is 688192
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E5-A2PC-01Z-00-DX1.409697C6-097B-4B24-A54B-B52BEC5A0A9B.pkl
File Size in Bytes is 740182
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E5-A4TZ-01Z-00-DX1.08FA5E08-5AF7-461E-8EBC-200BF969E505.pkl
File Size in Bytes is 929238
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E5-A4U1-01Z-00-DX1.A088BCB3-86D7-4895-A168-00981B44EF78.pkl
File Size in Bytes is 665256
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A3X6-01Z-00-DX1.5566A0E9-E1C3-4F97-8C82-D2FF3FE3FD8D.pkl
File Size in Bytes is 352085
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A3Y1-01Z-00-DX1.D3E81A0B-1D20-4916-8872-81D469A1E276.pkl
File Size in Bytes is 512735
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A4IJ-01Z-00-DX1.7215592C-D179-4EE8-81F7-B3E32AE0D830.pkl
File Size in Bytes is 787814
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A4XJ-01Z-00-DX1.70DA8872-34A6-41B7-8D17-2B15C80EF5CF.pkl
File Size in Bytes is 555615
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A519-01Z-00-DX1.F197805D-A2DB-4207-91EC-A9AE1FE16C53.pkl
File Size in Bytes is 382365
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A541-01Z-00-DX1.8387CEF8-706B-486C-BC07-783EC1016BCC.pkl
File Size in Bytes is 905728
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A5KE-01Z-00-DX1.BDCD4071-5EE5-4863-A722-DAA32F3A7FB4.pkl
File Size in Bytes is 230823
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A5KF-01Z-00-DX1.61663245-91CA-423F-9639-30B9F7E216C4.pkl
File Size in Bytes is 519863
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A677-01Z-00-DX1.D66285D0-F67B-4423-929B-DF34BBC55C80.pkl
File Size in Bytes is 376711
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A678-01Z-00-DX1.C589E72B-7214-4EE9-A796-869C2372DD67.pkl
File Size in Bytes is 868392
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A6MD-01Z-00-DX1.7E0C04CD-B51E-47F7-B79D-FEEC9B5023FF.pkl
File Size in Bytes is 488289
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A6ME-01Z-00-DX1.114098C0-6CD9-4240-B8F4-C2E6D86A6868.pkl
File Size in Bytes is 1036530
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A6MF-01Z-00-DX1.2B0C8CBF-3244-4D17-B9CA-3CBE000BEC29.pkl
File Size in Bytes is 306107
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A7DU-01Z-00-DX1.25C7F59E-1F03-47EF-9F17-DB9ADB16276E.pkl
File Size in Bytes is 1175326
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A7DV-01Z-00-DX1.FCE4752B-30BC-4747-A9F4-38141E09F005.pkl
File Size in Bytes is 1151130
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A7PW-01Z-00-DX1.27B92FC6-D50C-4816-A2C2-35E73D379DDD.pkl
File Size in Bytes is 1319063
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A7XN-01Z-00-DX1.5C955881-5B13-4D6B-B99C-E849ADCDE647.pkl
File Size in Bytes is 1197873
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A85H-01Z-00-DX1.0C1D94F2-1120-45AC-9053-7833DA12194F.pkl
File Size in Bytes is 1474275
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A8O7-01Z-00-DX1.E3D79C43-608D-40A1-9F65-0414FDF27741.pkl
File Size in Bytes is 727004
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A8O8-01Z-00-DX1.009173C4-BC8E-4B96-98FC-E24A39438F4E.pkl
File Size in Bytes is 644050
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A97P-01Z-00-DX1.09FD969F-62C2-4C79-A826-657A7991C87B.pkl
File Size in Bytes is 632710
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A97Q-01Z-00-DX1.821AF545-5433-4D2C-AACE-EA206E15B13D.pkl
File Size in Bytes is 176916
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B3-01Z-00-DX1.CD634C50-2746-468E-BEEC-50E76E400602.pkl
File Size in Bytes is 1253823
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B4-01Z-00-DX1.45B61DCC-09B4-4863-875A-ED1DEECE5F27.pkl
File Size in Bytes is 1371017
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B5-01Z-00-DX1.69DEA650-3D53-46AC-BB60-BF68C4413608.pkl
File Size in Bytes is 1304697
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B6-01Z-00-DX1.04CCC012-F2FF-4CBA-9A2C-8EC979427204.pkl
File Size in Bytes is 1043154
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B7-01Z-00-DX1.758419EB-E5A3-4383-817A-B3870FBA1776.pkl
File Size in Bytes is 1124020
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B8-01Z-00-DX1.85E75835-8607-47C3-B8BD-4F01E54E5574.pkl
File Size in Bytes is 734024
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3N5-01Z-00-DX1.C42537CC-55C9-43CD-921E-75D010B06582.pkl
File Size in Bytes is 1145190
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3N6-01Z-00-DX1.C94C21D1-83F2-45EE-A7BE-6A4E5C9B1A89.pkl
File Size in Bytes is 1126756
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3NA-01Z-00-DX1.2AD62CEE-0D76-4382-AE2E-9B7FCB1130D9.pkl
File Size in Bytes is 1285327
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SJ-01Z-00-DX1.CF7DF110-22A8-4071-9717-A71915407248.pkl
File Size in Bytes is 1390891
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SL-01Z-00-DX1.7B364C1F-3879-43C1-A3C7-B1CB03A7616B.pkl
File Size in Bytes is 1274237
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SM-01Z-00-DX1.D391C864-B5B5-4C4D-915F-FBD8BCACAD36.pkl
File Size in Bytes is 1471503
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SN-01Z-00-DX1.CB50ED59-FB7E-4892-AF72-6D297EC62466.pkl
File Size in Bytes is 1186747
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SO-01Z-00-DX1.C3A855BF-976F-4E2B-9E39-3D1AEA1A67F6.pkl
File Size in Bytes is 897914
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SP-01Z-00-DX1.05986238-A4B9-497D-9D00-8DB37B0040FE.pkl
File Size in Bytes is 837248
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SQ-01Z-00-DX1.86DF2023-BD72-4D84-B7AA-2330AA433DB9.pkl
File Size in Bytes is 1071274
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SR-01Z-00-DX1.7E2FB51A-9562-4B3D-8431-6283342B4311.pkl
File Size in Bytes is 777050
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SS-01Z-00-DX1.FEEC4D8E-E87D-4742-B377-5DA2999D6997.pkl
File Size in Bytes is 936618
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43N-01Z-00-DX1.57422C5F-A3A1-4595-9E06-C05C7FF5944B.pkl
File Size in Bytes is 1472871
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43P-01Z-00-DX1.792612F7-802C-4A90-A2B5-A6A82FCDE92F.pkl
File Size in Bytes is 1236937
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43S-01Z-00-DX1.528CA6F1-B53B-4396-B776-9761B578DCDE.pkl
File Size in Bytes is 1120132
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43U-01Z-00-DX1.003EC6EC-229E-4578-BF5B-1FB3EBF68845.pkl
File Size in Bytes is 814026
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43X-01Z-00-DX1.CB2A73D9-F64C-4553-8D11-4C25CEF98C45.pkl

File Size in Bytes is 1372601
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43Y-01Z-00-DX1.6516167F-A303-4524-98D6-E32CB521ED08.pkl
File Size in Bytes is 761424
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BR-01Z-00-DX1.53CA363B-8DA6-465A-9FEA-2D120B5787A8.pkl
File Size in Bytes is 1269341
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BS-01Z-00-DX1.A7155CEB-37C9-4AD2-B229-B76F18814585.pkl
File Size in Bytes is 1421889
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BT-01Z-00-DX1.2A4716E6-A5C0-4C69-82FD-E771ABB3B28D.pkl
File Size in Bytes is 1012768
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BU-01Z-00-DX1.94A8468C-59E7-4185-A877-CC271EA01C90.pkl
File Size in Bytes is 1009528
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BV-01Z-00-DX1.FD47C060-5104-45AC-95F8-0C4C5924FE26.pkl
File Size in Bytes is 1068502
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BX-01Z-00-DX1.172B23F4-4651-4C93-93E1-D0E81331DCA7.pkl
File Size in Bytes is 730208
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BY-01Z-00-DX1.9DF7C69C-FABA-46DC-9954-A7120C65061F.pkl
File Size in Bytes is 738848
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BZ-01Z-00-DX1.344B1F8F-3B3A-4D42-894E-27C5AE265F42.pkl
File Size in Bytes is 948428
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5C0-01Z-00-DX1.D11E8348-04DE-4934-B063-2E3F3AD8D110.pkl
File Size in Bytes is 1044198
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5C1-01Z-00-DX1.EAD87C49-A25C-4D37-AF27-E27F7016E065.pkl
File Size in Bytes is 1114514
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A62N-01Z-00-DX1.204E48B7-51D1-49D7-88F3-4BD33A07146A.pkl
File Size in Bytes is 865116
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A62O-01Z-00-DX1.4DD5E512-EF71-498B-8C25-18F42D0E1F1F.pkl
File Size in Bytes is 967906
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A62P-01Z-00-DX1.56B14555-896E-420A-AE8B-4E2D35D87871.pkl
File Size in Bytes is 1240969
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A62S-01Z-00-DX1.B35DA29A-6F19-4663-9DB2-AB57DAFC84A7.pkl
File Size in Bytes is 1577535
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TA-01Z-00-DX1.FC156A8A-B71C-46A3-B83F-99DB0FC41FC8.pkl
File Size in Bytes is 1112570
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TB-01Z-00-DX1.CDCC077C-2DFE-4B04-A0D0-69E1CFE80AC5.pkl
File Size in Bytes is 1019104
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TC-01Z-00-DX1.AC96EA62-D56E-4565-88E0-EBAEB8087C4F.pkl
File Size in Bytes is 998618
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TD-01Z-00-DX1.836B03BC-CD19-437D-A925-9862BB08AB1D.pkl
File Size in Bytes is 1155668
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TE-01Z-00-DX1.1CD738A0-1D6D-461B-9322-21F77CC3D167.pkl
File Size in Bytes is 1270529
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TF-01Z-00-DX1.15B2C3E0-A0D7-4879-82B1-6C9AB09AF8E2.pkl
File Size in Bytes is 1252563
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TG-01Z-00-DX1.C49D520E-3589-4623-9BBE-9676BAC83A8F.pkl
File Size in Bytes is 1093344
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TH-01Z-00-DX1.1791761E-876F-4AAB-A0B1-272A37A41E3A.pkl
File Size in Bytes is 1015936
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TI-01Z-00-DX1.A451F82D-983B-4646-BFC6-E40A66F2B9C8.pkl
File Size in Bytes is 943928
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TK-01Z-00-DX1.B685DA87-72A6-4C38-8AA1-40B6E543383C.pkl
File Size in Bytes is 859786
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX2.C4531060-32B7-4472-8B6D-3E4477810B9F.pkl
File Size in Bytes is 800848
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX6.28B723F7-1035-4DC2-8DB1-87F08166A9FA.pkl
File Size in Bytes is 912280
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX3.6709359F-68F9-4B02-B793-359B83F26372.pkl
File Size in Bytes is 418477
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX5.B0ABE3C5-94EC-4650-9698-0D4C57291267.pkl
File Size in Bytes is 578119
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX1.B36BF723-0E71-4FA9-A915-823634B91EA9.pkl
File Size in Bytes is 820974
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX4.7DDE20DA-894A-4751-A7C0-D5740CB30DD9.pkl
File Size in Bytes is 982776
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z9-01Z-00-DX1.012EC33E-2BEF-4EDB-81D5-6EAC32D90C87.pkl
File Size in Bytes is 1039914
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3ZE-01Z-00-DX2.147C2363-55A3-4C02-BAF5-4F1256E30542.pkl
File Size in Bytes is 994226
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3ZE-01Z-00-DX1.CD478617-4D80-4F36-8908-8480738367C6.pkl
File Size in Bytes is 927618
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3ZF-01Z-00-DX1.1B5E03AA-51A0-4E2B-A2B3-9652B1FA1D55.pkl
File Size in Bytes is 442743
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX4.5917B34B-0752-40A9-B749-FB4B5514229B.pkl
File Size in Bytes is 420997
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX5.8F79D0A8-5DE6-4159-AA77-61DACB21E867.pkl
File Size in Bytes is 423481
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX2.B09F27BF-6786-4CC7-8471-5A73E048A813.pkl
File Size in Bytes is 427225
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX3.23DB58B1-62E3-4B74-AF08-198BD843FA22.pkl
File Size in Bytes is 470323
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX1.72748A33-5021-4AC6-AEF4-9BDA17233AB3.pkl
File Size in Bytes is 445119
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FT-A3EE-01Z-00-DX1.1CA5BFA3-F6F7-45DE-83EC-F328AC4EBE80.pkl
File Size in Bytes is 1584699
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FT-A61P-01Z-00-DX1.39960BA6-ECC6-4EE0-B3ED-F3991E3742F6.pkl
File Size in Bytes is 636850
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX4.8E4382A4-71F9-4BC3-89AA-09B4F1B54985.pkl
File Size in Bytes is 692116
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX3.6DD4B773-86DE-4D58-A405-3C1B45FD6004.pkl
File Size in Bytes is 810424
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX7.F421FDF6-AF52-44C9-8AB2-9E37E1B8C8CC.pkl
File Size in Bytes is 754906
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX2.42C4093A-A313-41E6-B2FD-B7928F9B32F9.pkl
File Size in Bytes is 993650
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX1.44DA27E7-C499-46A1-A871-DBA4E5BCAA6A.pkl
File Size in Bytes is 931974
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX5.94164B15-8070-4F16-B0A5-C9345E00BB83.pkl
File Size in Bytes is 976872
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX6.60307899-9A64-4176-8617-BEBEFEF81CEE.pkl
File Size in Bytes is 574661
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX8.59E69965-ADB5-4E9D-B455-D766A90EB2AD.pkl
File Size in Bytes is 653844
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EF-01Z-00-DX3.04EC2CA4-7CCF-4DB6-829D-9067E7EF07C4.pkl
File Size in Bytes is 1128232
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EF-01Z-00-DX2.90428613-C414-421F-9502-EADCEBC47184.pkl
File Size in Bytes is 858274
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EF-01Z-00-DX1.5FA6C53C-C749-46CE-B85C-DDFE27962F7C.pkl
File Size in Bytes is 906268
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EF-01Z-00-DX4.70FC5B2D-E8EC-41EE-99B7-CB3FFC0F4D98.pkl
File Size in Bytes is 915556
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX6.6EFFECC5-45F4-4828-8AD7-84E060E6FC9D.pkl
File Size in Bytes is 891038
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX7.79C8E05D-5640-49AC-923D-58030F64DD5A.pkl
File Size in Bytes is 970426
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX2.3DCD4041-FBE0-45B4-BD5B-6A9E8200289C.pkl
File Size in Bytes is 778778
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX1.BBADB2AF-BF32-4678-A54B-F82CA11DC715.pkl
File Size in Bytes is 847474
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX8.C3EB2C27-F483-4CE5-AF8D-2AF462AB296F.pkl
File Size in Bytes is 832496
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX5.B20A9A5E-23B7-4C19-A021-8B19D56C80B2.pkl
File Size in Bytes is 849274
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX4.A156EE54-2814-415F-A7AD-9E408E7B0F50.pkl
File Size in Bytes is 617444
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX3.3FA3BE61-17DA-4CFE-8845-0889701340EB.pkl
File Size in Bytes is 507299
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EK-01Z-00-DX1.1F826341-0877-46E0-8DB7-9D01E8874614.pkl
File Size in Bytes is 720450
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EK-01Z-00-DX2.F68EC7A1-2B48-42EB-8621-39D8547E408D.pkl
File Size in Bytes is 696220
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EK-01Z-00-DX3.22408270-F6D1-4257-9014-E13C7B69A407.pkl
File Size in Bytes is 800848
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EL-01Z-00-DX1.CCC37120-A9F0-4278-9EA6-6CD1A132596C.pkl
File Size in Bytes is 952604
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EL-01Z-00-DX2.2E59E1ED-C518-46EC-B60A-B083BA3A77C7.pkl
File Size in Bytes is 1295083
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX8.04D3920F-D1FD-4B37-8229-877FC64C3492.pkl
File Size in Bytes is 632818
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX4.BE1980E2-83B2-4E04-A6A4-9B71B15793B5.pkl
File Size in Bytes is 224595
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX2.94CC403C-1986-4906-AF11-92E349C8A114.pkl
File Size in Bytes is 261139
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX6.8FBEA23E-DC4C-4420-A72A-FDDC0CC1F80A.pkl
File Size in Bytes is 276009
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX1.E2FEF97D-F947-4497-8605-BBBFC3EC665B.pkl
File Size in Bytes is 179472
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX7.5784EBED-47AE-4ADA-84F2-3E58965EE2BC.pkl
File Size in Bytes is 338079
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX5.85F4C6CF-E10B-4EF7-B477-D42E9F78247F.pkl

File Size in Bytes is 355361
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX3.F64AE021-27AB-4B3C-9DD2-9B8A358326C3.pkl
File Size in Bytes is 317953
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX1.B80524C7-9705-461E-852E-DA99575FABF0.pkl
File Size in Bytes is 951128
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX4.F8B9CC1E-CDC8-4335-82DD-4BE4F6A35CEF.pkl
File Size in Bytes is 690388
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX5.3576FA08-47B1-4A10-94F1-5F5A57A7835E.pkl
File Size in Bytes is 823134
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX3.4127F544-FC83-44F6-85CD-3F1542785E71.pkl
File Size in Bytes is 202921
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX7.03160CC5-FC81-4A8D-96D4-BCEBADCDF599.pkl
File Size in Bytes is 444111
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX2.CA66A071-D602-41CD-BD39-4AF1FD7BFC43.pkl
File Size in Bytes is 818166
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX6.FF3254DB-03CE-48A3-8C68-E0BAE60694F6.pkl
File Size in Bytes is 690676
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IB-01Z-00-DX2.233CCEF1-7332-4940-84A6-7CD6ADE8272E.pkl
File Size in Bytes is 723404
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IB-01Z-00-DX4.2AECF9F2-3DC4-4474-9D1D-13B40EC9DBDD.pkl
File Size in Bytes is 234603
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IB-01Z-00-DX1.27F44B48-11D5-438D-B568-E099C05AD428.pkl
File Size in Bytes is 698992
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IB-01Z-00-DX3.87062FFE-72F3-48E0-A9CD-71F5FF3819D3.pkl
File Size in Bytes is 873900
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IE-01Z-00-DX1.DEEF9D35-CE4C-499F-9481-9E9E379694FC.pkl
File Size in Bytes is 1244607
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IE-01Z-00-DX2.48A6B225-8608-41A5-9268-63262105DDED.pkl
File Size in Bytes is 792458
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3VY-01Z-00-DX1.E571536B-7C5A-48DC-9CED-5ACA78DDD43F.pkl
File Size in Bytes is 443931
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX3.A193600C-0B83-4FEB-AB0C-DECF6FC78E1A.pkl
File Size in Bytes is 244361
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX2.B9AC70CF-591B-4AFF-A8C0-F43A9C91CFF9.pkl
File Size in Bytes is 619604
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX4.6E70BFE1-D95F-48A9-9897-97322FBA937A.pkl
File Size in Bytes is 845276
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX1.F4F8CCF4-E74C-4B07-B385-5E30E0E1BB0D.pkl
File Size in Bytes is 560441
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX5.57084980-934B-4A4A-A720-24FA2E9E0CB2.pkl
File Size in Bytes is 672206
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3C-01Z-00-DX2.00AE9115-F979-4DD6-8364-96493CC00835.pkl
File Size in Bytes is 1319567
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3C-01Z-00-DX1.D2CA01A1-A2F3-4624-A022-BAEA71AA67AC.pkl
File Size in Bytes is 925854
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3D-01Z-00-DX1.8C31FE8D-13F9-49FF-A4FB-2D004B109394.pkl
File Size in Bytes is 83594
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX1.C63054C3-6DBF-42A1-ADA3-79FF26ED02B3.pkl
File Size in Bytes is 951344
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX4.8DD53108-E08F-4F3C-80EE-E31D934B9BDF.pkl
File Size in Bytes is 1197225
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX8.D27EA057-F808-44FE-AF5D-9F7237D59488.pkl
File Size in Bytes is 1100186
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX3.360ECD0E-F773-4153-A782-EDED1819BDBA.pkl
File Size in Bytes is 1172554
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX9.77E9E77B-0A41-4045-A1EE-19FEC7259910.pkl
File Size in Bytes is 948212
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX2.8991BE4B-303B-4177-9046-2D6412D0698E.pkl
File Size in Bytes is 1237873
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX6.AD188C41-F5A7-49ED-9C1A-F7E956A34AC5.pkl
File Size in Bytes is 1072498
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX5.A1D2BBD8-A1B6-46E1-8D22-C897019DB41F.pkl
File Size in Bytes is 1059284
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX7.61BFF067-ADE1-4879-8746-34F034B06A2A.pkl
File Size in Bytes is 913072
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3BM-01Z-00-DX1.8880FA8C-8607-4C55-A619-2C8D7F2866EF.pkl
File Size in Bytes is 107572
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3I6-01Z-00-DX1.47650F7B-0AD3-49C9-AB9E-40383C7D07AC.pkl
File Size in Bytes is 124674
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3OO-01Z-00-DX1.F2A671AF-74E6-4F9B-8ABC-6A10EB1F68A8.pkl
File Size in Bytes is 301319
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3RB-01Z-00-DX1.C0011A55-EA8A-436B-BBCA-342B96803B22.pkl
File Size in Bytes is 99544
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3RC-01Z-00-DX1.DC4B31BC-5C7F-421A-88CD-38428051A653.pkl
File Size in Bytes is 325587
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3RD-01Z-00-DX1.40B5E97D-B45F-4C93-A41B-0F17B757491B.pkl
File Size in Bytes is 1277225
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3WC-01Z-00-DX1.D8F5CD43-7338-414C-ADE8-AC0BBC6A871C.pkl
File Size in Bytes is 82982
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3YS-01Z-00-DX1.97B4664A-9D8B-460D-B4A4-89855D3DB0C2.pkl
File Size in Bytes is 257359
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A4ZW-01Z-00-DX1.6ECD07FB-AE2C-4A04-812F-F5FB2B31F820.pkl
File Size in Bytes is 809632
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A6I1-01Z-00-DX1.2AD569EC-372B-4B72-A222-924091ADEE99.pkl
File Size in Bytes is 91084
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A6I3-01Z-00-DX1.1B3D09B9-14FB-4236-9354-3E5CC59354A7.pkl
File Size in Bytes is 331743
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A2C5-01Z-00-DX1.3A81505E-5BF9-466C-938B-28909CD88193.pkl
File Size in Bytes is 302723
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A3OP-01Z-00-DX1.A1D66E35-8E4D-4420-AD57-D45016D016D5.pkl
File Size in Bytes is 438747
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A3OQ-01Z-00-DX1.ED8C9F09-57A9-4915-950A-A61FE2FE8538.pkl
File Size in Bytes is 312049
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A3OS-01Z-00-DX1.5EA796F4-E7F3-4421-BDEA-522BED020B5B.pkl
File Size in Bytes is 256315
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A6C6-01Z-00-DX1.5C5F2FA2-6284-4DD8-BE73-D13A88988640.pkl
File Size in Bytes is 226323
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A76B-01Z-00-DX1.C299842E-F204-4071-AD72-1E1A303B396B.pkl
File Size in Bytes is 151894
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42P-01Z-00-DX2.3A4A8614-693F-452C-BB2C-AD16D5AC6F12.pkl
File Size in Bytes is 1059860
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42P-01Z-00-DX1.3A4A8614-693F-452C-BB2C-AD16D5AC6F12.pkl
File Size in Bytes is 1145514
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42Q-01Z-00-DX2.91D8B0D2-538F-4411-9B3C-0E1FAE1A0606.pkl
File Size in Bytes is 502149
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42Q-01Z-00-DX1.91D8B0D2-538F-4411-9B3C-0E1FAE1A0606.pkl
File Size in Bytes is 646318
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42R-01Z-00-DX1.1A14BFD8-DE37-4D10-ACB6-317ECEB930CA.pkl
File Size in Bytes is 1034550
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42R-01Z-00-DX2.B54CCE4D-E4DE-473B-B7C6-5A349FD7F55C.pkl
File Size in Bytes is 598650
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A762-01Z-00-DX1.F01B133E-3744-4430-9752-FDD25EEF58A3.pkl
File Size in Bytes is 1083912
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A763-01Z-00-DX1.2B511825-320B-48D7-B8D6-D97894C02667.pkl
File Size in Bytes is 736616
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A764-01Z-00-DX1.213E1BDD-33DE-454E-BE79-940E5D793D42.pkl
File Size in Bytes is 1056692
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A766-01Z-00-DX1.72BD6744-E817-4B15-BF58-64BDBC1943FF.pkl
File Size in Bytes is 813126
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A767-01Z-00-DX1.A8B13490-D25A-45E1-A2D8-02125DB3A6B2.pkl
File Size in Bytes is 587200
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-AATO-01Z-00-DX1.1F0F2098-E4DF-4AA3-819E-E0DE23C5A0BE.pkl
File Size in Bytes is 779678
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-AATP-01Z-00-DX1.0D8EC37C-88E7-49D5-A76D-F0A4A3FD8AE4.pkl
File Size in Bytes is 891542
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-AATQ-01Z-00-DX1.6D436809-1238-44CA-9CFC-03DC2277C192.pkl
File Size in Bytes is 874296
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3JV-01Z-00-DX1.F071374F-1290-4A36-9466-D6F1F3EBC17E.pkl
File Size in Bytes is 781838
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3JW-01Z-00-DX1.152AD6E5-D30A-4D94-A793-3DDF3828625C.pkl
File Size in Bytes is 603366
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3JX-01Z-00-DX1.36A00B8A-662D-43EE-AB52-CBBBF373BCFF.pkl
File Size in Bytes is 737120
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3JZ-01Z-00-DX1.5DFDE227-D52D-481F-A8D8-28DF25096BD9.pkl
File Size in Bytes is 872820
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QF-01Z-00-DX1.C59696CF-C415-46AD-B6D6-70A022AC10FA.pkl
File Size in Bytes is 904648
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QG-01Z-00-DX1.4A550B20-2A4C-48E5-BFE2-6EBBC59E4041.pkl
File Size in Bytes is 1104290
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QH-01Z-00-DX1.A87C25E1-8199-4557-944B-9ABD1A70ADE9.pkl
File Size in Bytes is 601782
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QI-01Z-00-DX1.0B9889AC-06C7-405F-B300-D93EB0F19D9A.pkl
File Size in Bytes is 799264
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QK-01Z-00-DX1.DACDDD23-0DD8-44EC-9FE2-945ADEA8AC43.pkl
File Size in Bytes is 1223723
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A40E-01Z-00-DX1.6313DD1A-6E65-4775-82DC-58AD4EF81D32.pkl
File Size in Bytes is 776330
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A40G-01Z-00-DX1.AD1A709F-A10C-4E69-B4ED-6361777361FD.pkl
File Size in Bytes is 822234
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A6ZA-01Z-00-DX1.6EBD225D-5EE2-4F0A-BC07-1EF5CEBFE25A.pkl
File Size in Bytes is 1343545
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-H4-A2HO-01Z-00-DX1.37FB76BF-EA5F-430D-89A4-8789ECACC5DB.pkl
File Size in Bytes is 988752
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-H4-A2HQ-01Z-00-DX1.DFBDDFDD-0C65-4130-96F5-4E3838190D13.pkl

File Size in Bytes is 695788
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-HQ-A2OE-01Z-00-DX1.6F764592-DFDC-4636-BE91-3F1F92EE5A65.pkl
File Size in Bytes is 361519
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-HQ-A2OF-01Z-00-DX1.6D50B772-71C3-40C3-94CF-969946799028.pkl
File Size in Bytes is 350717
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-HQ-A5ND-01Z-00-DX1.EDDFB95C-827E-4533-B49A-56612BC4D9DD.pkl
File Size in Bytes is 359465
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-HQ-A5NE-01Z-00-DX1.8046B606-085B-406F-A8D7-92A3E021020A.pkl
File Size in Bytes is 153082
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A3WS-01Z-00-DX1.6814457F-C30E-4B3D-BA37-B701FF591BFE.pkl
File Size in Bytes is 1396147
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A3WU-01Z-00-DX1.DD4CA7B4-7950-4B7A-820A-74C763AFAE65.pkl
File Size in Bytes is 878220
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A3WV-01Z-00-DX1.F44E3C25-920C-4730-9019-D1E993121F08.pkl
File Size in Bytes is 1572603
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A4AB-01Z-00-DX1.88A9D084-1B3B-4B13-AAD7-18C6587624C0.pkl
File Size in Bytes is 647470
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A4AC-01Z-00-DX1.DED1674F-953D-40DB-85AE-9CD595248EC7.pkl
File Size in Bytes is 1230133
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A54R-01Z-00-DX1.66AAF596-8C68-4857-9944-226F39E82CA8.pkl
File Size in Bytes is 466973
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A5RH-01Z-00-DX1.8AA2FC59-CDA4-49F5-BAB7-B14B6792FAF8.pkl
File Size in Bytes is 1207343
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A5RI-01Z-00-DX1.A56C3CF4-543E-46D6-BA50-52A4C790FAE8.pkl
File Size in Bytes is 1486517
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A5RJ-01Z-00-DX1.DFDDA8B5-E80F-4BF9-87E3-EA75E294ABF5.pkl
File Size in Bytes is 920058
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A6FZ-01Z-00-DX1.E4BB7534-1719-45C7-8E0F-78558DB9AD37.pkl
File Size in Bytes is 861298
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A6MB-01Z-00-DX1.4A6009D3-05D9-4E8B-8EB2-4A52B5B6FED8.pkl
File Size in Bytes is 741946
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A83P-01Z-00-DX1.6B9251BD-650E-4F69-BE8F-AB0BE5DC90FB.pkl
File Size in Bytes is 910948
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-AAQO-01Z-00-DX1.7533831F-414B-4BA5-9CDA-D8B24E579962.pkl
File Size in Bytes is 971974
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-LC-A66R-01Z-00-DX1.9D753031-E31A-4E0E-B937-E0D3C47CFFB9.pkl
File Size in Bytes is 673970
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-LT-A5Z6-01Z-00-DX1.F547947F-DDB8-4DFF-B08E-FB494F7F044B.pkl
File Size in Bytes is 589756
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-LT-A8JT-01Z-00-DX1.8D04BB53-EEA9-401B-B92E-8EB9DEEE7E4E.pkl
File Size in Bytes is 999410
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-MV-A51V-01Z-00-DX1.5D626704-0803-4912-96D5-FB1EEFA509FB.pkl
File Size in Bytes is 80966
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-PQ-A6FI-01Z-00-DX1.EC3791D8-B5D2-468A-9FB7-D0217CD02DFB.pkl
File Size in Bytes is 741766
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-PQ-A6FN-01Z-00-DX1.58FC60E8-7386-4E57-804D-6AD103AE0FDC.pkl
File Size in Bytes is 602862
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-S5-A6DX-01Z-00-DX1.70418D45-0396-4838-BF0C-588C7719A131.pkl
File Size in Bytes is 544167
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-S5-AA26-01Z-00-DX1.10D28D0C-D537-485E-A371-E3C60ED66FE7.pkl
File Size in Bytes is 554715
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-SY-A9G0-01Z-00-DX1.6F019857-03C8-4B2B-8892-32CBF3EB303F.pkl
File Size in Bytes is 211597
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-SY-A9G5-01Z-00-DX1.CE221A12-59FC-4482-9BD5-7082A2EA4E61.pkl
File Size in Bytes is 454445
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78K-01Z-00-DX1.329D9BFF-A204-4A7D-8767-B39F34179708.pkl
File Size in Bytes is 494841
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78L-01Z-00-DX1.8955EB83-E4AE-452E-8B68-83C4B8BED6D5.pkl
File Size in Bytes is 575669
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78M-01Z-00-DX1.9C08E77F-E63B-480E-A4D5-1576EF802152.pkl
File Size in Bytes is 693808
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78N-01Z-00-DX1.31873403-A629-4ED9-B2AF-14817689BB3B.pkl
File Size in Bytes is 788498
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78O-01Z-00-DX1.6DDC084F-A086-4B5B-90B6-9C45E842A5FA.pkl
File Size in Bytes is 931794
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78P-01Z-00-DX1.B6783816-0322-4453-BC80-20ED79A40588.pkl
File Size in Bytes is 1366767
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A8OB-01Z-00-DX1.9DD447FB-44F0-4FFF-8293-9FF0D54A96A0.pkl
File Size in Bytes is 1162796
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A8OC-01Z-00-DX1.EE2DF9C6-3CA9-411D-85D4-D1831F14AAFD.pkl
File Size in Bytes is 976908
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A8OD-01Z-00-DX1.3985C497-D586-4AB9-A635-63A7946C5A2E.pkl
File Size in Bytes is 678290
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PA-01Z-00-DX1.A83A79FB-810C-42A4-8EC7-A3328D79542D.pkl
File Size in Bytes is 1232437
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PB-01Z-00-DX1.4ACBFEEA-703A-47AF-A67D-359B9F027DD0.pkl
File Size in Bytes is 778454
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PD-01Z-00-DX1.55AF21E3-74DF-4D18-ADA4-A2A12665DF0A.pkl
File Size in Bytes is 882072
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PE-01Z-00-DX1.19205347-9969-475E-9293-E99D4833E462.pkl
File Size in Bytes is 861226
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PF-01Z-00-DX1.8A5B3826-48D2-42AE-A4DE-C0BB90134FCB.pkl
File Size in Bytes is 678614
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PH-01Z-00-DX1.7FAA1EC7-C2BB-47E0-BCEB-5D4095078B2E.pkl
File Size in Bytes is 850786
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HB-01Z-00-DX1.D6874152-D20A-4CA4-8E8B-8CBAB5F7D7B5.pkl
File Size in Bytes is 629144
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HC-01Z-00-DX1.BF199254-2954-4836-B037-E10493275D8C.pkl
File Size in Bytes is 903388
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HD-01Z-00-DX1.809538C0-0D52-4DA5-AA7D-EDA7B363BF36.pkl
File Size in Bytes is 872820
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HE-01Z-00-DX1.A0E05485-2A24-4BD0-8B2F-E0D9641ADD9F.pkl
File Size in Bytes is 833936
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HF-01Z-00-DX1.119AB9B9-73CE-4DE3-B305-4872F704E3E4.pkl
File Size in Bytes is 1147746
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HG-01Z-00-DX1.9D3970D1-C598-4F4C-ABBD-92C55C7C837A.pkl
File Size in Bytes is 905224
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HH-01Z-00-DX1.22E9DD6D-F231-422F-A349-9FF60B65D50E.pkl
File Size in Bytes is 1027458
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HI-01Z-00-DX1.1BA3EF33-D4D5-4213-833D-A7F8C0EFFF02.pkl
File Size in Bytes is 1036818
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SG-01Z-00-DX1.6D50B71D-9736-46F9-B527-63565FC65AF2.pkl
File Size in Bytes is 422509
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SH-01Z-00-DX1.B1E33049-ABB8-4F2F-9D2D-503E48B8CDE5.pkl
File Size in Bytes is 501537
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SI-01Z-00-DX1.537F0394-40FE-4CB7-8524-7BC34F624C15.pkl
File Size in Bytes is 906160
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SJ-01Z-00-DX1.AED4FF1B-441D-47EE-B7E5-CC6C595D3D98.pkl
File Size in Bytes is 1077610
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SK-01Z-00-DX1.1D198106-323F-463B-832B-CB3A03E7B343.pkl
File Size in Bytes is 928986
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SL-01Z-00-DX1.AA56A70C-28E1-4140-9B15-72AB0D5051A6.pkl
File Size in Bytes is 779138
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SM-01Z-00-DX1.7AADC753-E07E-44A5-91EC-D1740ED5A168.pkl
File Size in Bytes is 755338
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SP-01Z-00-DX1.7F3BF700-89AD-4045-AFCD-C94F1F959B41.pkl
File Size in Bytes is 799084
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9ST-01Z-00-DX1.C135C4EB-6A64-4B9E-A8A0-87B72594568C.pkl
File Size in Bytes is 407927
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SU-01Z-00-DX1.35E2DDBE-5BB9-443B-A3D5-20F77D1C6B92.pkl
File Size in Bytes is 767580
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SV-01Z-00-DX1.2ACAA181-2EFA-4E63-B692-D968BCC56031.pkl
File Size in Bytes is 1044702
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SW-01Z-00-DX1.3FC62DD6-E5D2-4F74-A937-A2A62946E5C0.pkl
File Size in Bytes is 679514
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SX-01Z-00-DX1.6DB4572E-915C-491F-BE68-99C019799E20.pkl
File Size in Bytes is 762432
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SY-01Z-00-DX1.758C5D9F-274B-4D4A-92D3-78728CB35139.pkl
File Size in Bytes is 885854
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SZ-01Z-00-DX1.42A301F5-42E9-4618-A85A-51C1AEC8B8D1.pkl
File Size in Bytes is 1028862
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T0-01Z-00-DX1.63C52F23-3DE3-4D3A-914E-E7F3CB23D410.pkl
File Size in Bytes is 677642
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T2-01Z-00-DX1.E33F796C-46EB-44C4-AC65-ED6098EE3043.pkl
File Size in Bytes is 1085388
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T3-01Z-00-DX1.408F9901-F442-420B-BE89-ADBD01D1E256.pkl
File Size in Bytes is 895286
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T4-01Z-00-DX1.1F44D95D-E341-4FBA-BCB5-43E89E6C359E.pkl
File Size in Bytes is 670046
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T5-01Z-00-DX1.B0A44AF2-B075-4280-809E-DDACCDB20E3D.pkl
File Size in Bytes is 678038
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T6-01Z-00-DX1.57AE17FC-DB4C-4D2B-A53F-A259E8482064.pkl
File Size in Bytes is 1398883
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T8-01Z-00-DX1.C18E4176-C0C1-4F5A-B128-23DF5CE77C05.pkl
File Size in Bytes is 662880
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAME-01Z-00-DX1.90E1555F-CBAF-434C-9C7E-5BAC38069AC7.pkl
File Size in Bytes is 724916
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMF-01Z-00-DX1.01371D44-969E-44C8-993B-13B83D9E4F0F.pkl
File Size in Bytes is 377251
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMG-01Z-00-DX1.E0234C99-915C-4190-805A-147D4E3B10D9.pkl
File Size in Bytes is 641206
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMH-01Z-00-DX1.AB5E1C7D-C3BF-4A69-B614-0ED69F8A3C07.pkl
File Size in Bytes is 863026
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMJ-01Z-00-DX1.726E3D84-8370-45AC-9C98-ACA30CAB2359.pkl
File Size in Bytes is 579199
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAML-01Z-00-DX1.E2780FA6-641F-4A5A-B755-9ABD3C57C13E.pkl
File Size in Bytes is 1466823
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMQ-01Z-00-DX1.E8D304A9-4BD0-4C62-8B01-4C00994F8EE9.pkl
File Size in Bytes is 652548
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMR-01Z-00-DX1.7BFF4F04-9B60-41AA-9977-AF63547748AB.pkl
File Size in Bytes is 800056
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMT-01Z-00-DX1.F5A3715A-55DC-46C1-A6F9-4B1BFE1176EC.pkl
File Size in Bytes is 1207595
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMW-01Z-00-DX1.875DED6D-805B-418C-8C9E-AE45FDECC504.pkl
File Size in Bytes is 920454
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMX-01Z-00-DX1.453214DD-54FF-42DF-8BD6-E6BC4B376EFF.pkl

File Size in Bytes is 754582
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMY-01Z-00-DX1.44D91D18-357D-4FB2-A7CA-38792E3CB839.pkl
File Size in Bytes is 860110
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMZ-01Z-00-DX1.05AB4629-F59E-4877-B7F3-CF4336557EE0.pkl
File Size in Bytes is 607794
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN0-01Z-00-DX1.B9D6C207-F124-4558-ABD4-2846F42C5F66.pkl
File Size in Bytes is 739750
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN1-01Z-00-DX1.F6F0E65A-0D01-4C00-AEAC-359D52C802BF.pkl
File Size in Bytes is 829328
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN2-01Z-00-DX1.EB523A3A-0DE0-4FFC-9FE7-CF4FB2FB36CF.pkl
File Size in Bytes is 597282
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN3-01Z-00-DX1.2F004F0A-57C1-42CA-A07C-CE0FE8F876D5.pkl
File Size in Bytes is 688660
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN4-01Z-00-DX1.F9F1800B-9945-4695-B851-A4585E9D56D6.pkl
File Size in Bytes is 963334
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN5-01Z-00-DX1.DACB5253-366B-40A2-AD52-376F26C103A6.pkl
File Size in Bytes is 717102
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN7-01Z-00-DX1.B8EDF045-604C-48CB-8E54-A60564CAE2AD.pkl
File Size in Bytes is 921786
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN8-01Z-00-DX1.2962EEBB-A4F1-4958-85C9-480B7CA769A8.pkl
File Size in Bytes is 535453
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YC-A89H-01Z-00-DX1.ACE5AFD4-274B-4579-9B0E-EDD8D9251A8C.pkl
File Size in Bytes is 781982
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YC-A8S6-01Z-00-DX1.6B92FB17-2000-48B0-B7AE-6C8766D958E2.pkl
File Size in Bytes is 710046
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YC-A9TC-01Z-00-DX1.D7C1A85C-C39C-436F-A22A-2A09558CCF18.pkl
File Size in Bytes is 379665
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YC-A9TC-01Z-00-DX2.F74F61C0-CB9F-4E6E-BDA7-D206ECBBDEFC.pkl
File Size in Bytes is 412499
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YF-AA3L-01Z-00-DX1.56C211C1-20C7-4000-9C39-F76919ADA592.pkl
File Size in Bytes is 808840
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YF-AA3M-01Z-00-DX1.28587CDB-1FDF-4FD0-B809-86C7EA64562A.pkl
File Size in Bytes is 1694405
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R0-01Z-00-DX1.B9FD30D2-807E-49F7-A9E0-C58226EDEF13.pkl
File Size in Bytes is 1180843
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R1-01Z-00-DX1.74520759-D448-45B5-B8AD-45502C99A519.pkl
File Size in Bytes is 738164
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R2-01Z-00-DX1.D5BC88BD-594B-4EAA-988E-2577E48FEE15.pkl
File Size in Bytes is 1092048
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R3-01Z-00-DX1.AF828281-A45C-47D1-9FE3-CE7B9E105914.pkl
File Size in Bytes is 1176091
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R4-01Z-00-DX1.0A115B7F-FB7F-4D82-953F-62BF64C1245F.pkl
File Size in Bytes is 1027530
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R5-01Z-00-DX1.50B18159-9376-411A-B519-12BB50D06DFC.pkl
File Size in Bytes is 544383
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R7-01Z-00-DX1.AF323B5F-EE04-422E-B635-1050870897DC.pkl
File Size in Bytes is 1215947
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R9-01Z-00-DX1.8E68A35C-F2B7-410E-A1DE-3C460D67DB85.pkl
File Size in Bytes is 835160
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RC-01Z-00-DX1.A3F3826E-2BDE-48C3-9854-1061273AF9DC.pkl
File Size in Bytes is 729164
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RD-01Z-00-DX1.84823027-AA0A-412A-9DEA-EFBB8406FD9C.pkl
File Size in Bytes is 1090752
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RE-01Z-00-DX1.6E1EF772-E62D-4D9F-8688-43AAF764A6E6.pkl
File Size in Bytes is 788426
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RF-01Z-00-DX1.948A32F2-EF55-44E8-BC52-6FCF4A3411BF.pkl
File Size in Bytes is 1480361
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RG-01Z-00-DX1.E9C92201-31AD-4D7E-87C0-64842D705380.pkl
File Size in Bytes is 1253463
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RL-01Z-00-DX1.6A6B23B8-78D2-4468-8B25-A2D94130722C.pkl
File Size in Bytes is 435363
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RM-01Z-00-DX1.68758A74-2409-48F4-811A-EA42B4F8F942.pkl
File Size in Bytes is 1364067
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RN-01Z-00-DX1.262DCE43-154D-492E-80C3-6F8C8D4058D0.pkl
File Size in Bytes is 883190
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4N-01Z-00-DX1.F176510E-CF8B-4681-9CDE-B6210D8DC88F.pkl
File Size in Bytes is 1010824
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4R-01Z-00-DX1.2CDCECED-FC91-48D4-AAAC-4452B7C2F218.pkl
File Size in Bytes is 720738
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4T-01Z-00-DX1.3AC48F6E-01E2-4C20-BEFE-3B4A150DFF67.pkl
File Size in Bytes is 353381
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4U-01Z-00-DX1.E7FBFD1C-E974-4B9C-8DA8-D14FEC22D117.pkl
File Size in Bytes is 771000
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4V-01Z-00-DX1.04E4C701-9AA4-41DC-A615-4EB695CE8E3C.pkl
File Size in Bytes is 679046
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4W-01Z-00-DX1.1B35CC2D-3115-4BCF-8BAD-164806CAA7D3.pkl
File Size in Bytes is 665040
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4X-01Z-00-DX1.925D02DA-FAFF-4F2B-A3CE-BF884E5C4C03.pkl
File Size in Bytes is 906988
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA51-01Z-00-DX1.128C9731-C206-4E71-9A64-864FA9FD7E96.pkl
File Size in Bytes is 840920
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA52-01Z-00-DX1.BABC9074-8AF5-42E7-B3F8-39590121B620.pkl
File Size in Bytes is 1160780
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA53-01Z-00-DX1.04E05AAC-DAE2-428F-98DD-37F2B414E818.pkl
File Size in Bytes is 1664701
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA54-01Z-00-DX1.9118BB51-333A-4257-A797-75620F1E7AD6.pkl
File Size in Bytes is 1061912
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA58-01Z-00-DX1.85C3611E-11FA-4AAE-B880-C67C8CC7383B.pkl
File Size in Bytes is 1181383
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA5H-01Z-00-DX1.2B5DF00E-E0FD-4C58-A82C-3107A27F99D6.pkl
File Size in Bytes is 982632
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA5N-01Z-00-DX1.A207E3EE-CC7D-4267-A77E-71BBD15B95A8.pkl
File Size in Bytes is 1040346
/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA5P-01Z-00-DX1.B91697A2-A186-4E67-A818-56271D2009A9.pkl
File Size in Bytes is 1297137

[]

## Generate Embeddings

In [5]:
for i in patches_pkl:
    k = i.replace('.pkl','.npy')
    print(i)
    generate_embeddings(patch_info_file= i,
                        image_file= k,
                        architecture="resnet50",
                        image_stack=True)

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KO-01Z-00-DX1.195576CF-B739-4BD9-B15B-4A70AE287D3E.pkl

912it [01:07, 13.41it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KP-01Z-00-DX1.3CDF534E-958F-4467-AA7E-FD3C5A86AAAA.pkl

1224it [01:30, 13.55it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KP-01Z-00-DX2.718C82A3-252B-498E-BFBE-F4E4EB431BF5.pkl

1282it [01:36, 13.32it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KQ-01Z-00-DX1.1C8CB2DD-5CC6-4E99-A0F9-32A0F598F5F9.pkl

701it [00:51, 13.67it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KR-01Z-00-DX1.D6A4BD2D-18F3-4FA6-8272-60392DDAF7B5.pkl

1429it [01:44, 13.70it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KT-01Z-00-DX2.A06896B2-FC9A-430D-8F59-C89EEA002C8B.pkl

1576it [01:57, 13.43it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KT-01Z-00-DX1.ADD6D87C-0CC2-4B1F-A75F-108C9EB3970F.pkl

1443it [01:49, 13.12it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KW-01Z-00-DX1.CECFDA2E-2CE7-4115-B4E6-A3D75B130232.pkl

1374it [01:40, 13.73it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-2F-A9KW-01Z-00-DX2.10D33B2F-631F-4E3D-BF53-24D40A1088A3.pkl

696it [00:51, 13.64it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7M-01Z-00-DX1.05317C75-A8F3-4124-95D2-F039BEFFE63A.pkl

818it [01:01, 13.40it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7N-01Z-00-DX1.10AA3499-6678-4DB2-9466-9CB3EA25CBB6.pkl

856it [01:04, 13.31it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7Q-01Z-00-DX1.9C30EAED-8DE3-437C-8852-0C64B415AFA8.pkl

691it [00:50, 13.59it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7R-01Z-00-DX1.8FBDAFEB-265F-4594-9069-E34BAB417FC4.pkl

536it [00:40, 13.23it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7S-01Z-00-DX1.35242781-51FD-4883-A347-6EADC40E39C2.pkl

603it [00:47, 12.61it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7W-01Z-00-DX1.9BE6DF4E-480F-483E-8299-D949B5C09B4B.pkl

810it [01:00, 13.46it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA7Y-01Z-00-DX1.5771D5DA-5163-4F6C-A99A-DA682D3F059F.pkl

610it [00:44, 13.81it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA80-01Z-00-DX1.303549D2-42A5-46C4-AD9D-D72337B416E5.pkl

871it [01:04, 13.51it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA81-01Z-00-DX1.797432E9-56C6-4142-9AA4-233D7C565BF1.pkl

501it [00:41, 12.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA82-01Z-00-DX1.D18C9339-88DE-48E7-9D75-1ACB95483F7D.pkl

822it [01:03, 13.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA83-01Z-00-DX1.432ADCAA-36B5-4F9F-B4AE-6D755805FEF5.pkl

696it [00:53, 13.10it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA84-01Z-00-DX1.604B60F3-1E19-4335-9F8D-0D6920B1ACF8.pkl

693it [00:51, 13.37it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA86-01Z-00-DX1.C4DC6342-85A3-4F8A-BA6E-B63C554880B4.pkl

589it [00:46, 12.60it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA87-01Z-00-DX1.84170458-631E-49C5-9D7F-70126388ADE3.pkl

577it [00:41, 13.84it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-4Z-AA89-01Z-00-DX1.6DD89FC0-A062-41F1-AED3-FF8975FAADF3.pkl

905it [01:07, 13.50it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-5N-A9KI-01Z-00-DX1.1BAE5EFF-859F-4D0A-8DDC-527E2901F7D4.pkl

1169it [01:29, 13.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-5N-A9KM-01Z-00-DX1.5197F750-D17F-459B-B74D-846F5F50F7B7.pkl

369it [00:26, 13.92it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A0C8-01Z-00-DX2.1D788C7B-801F-4957-B1DE-43DCAA82A16A.pkl

266it [00:19, 13.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A0C8-01Z-00-DX1.E7FC7156-EF0C-4C79-93D1-1345ADB36A45.pkl

277it [00:20, 13.40it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13I-01Z-00-DX1.D08284EF-2E42-44FE-A3B9-BEF64076A86E.pkl

277it [00:20, 13.21it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13I-01Z-00-DX2.251412B0-EECB-420A-B963-B19432DB3F29.pkl

124it [00:09, 12.61it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13J-01Z-00-DX1.F2AFDD81-C88A-45EA-AC10-D9B38E878019.pkl

131it [00:10, 12.23it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A13J-01Z-00-DX2.289B5C8E-56AF-440D-A844-36BD98B573AF.pkl

100%|██████████| 48/48 [00:03<00:00, 13.40it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A3JM-01Z-00-DX1.33E53972-CEA4-4D84-A5D2-7DAD7B0C27F8.pkl

57it [00:04, 14.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A5ZZ-01Z-00-DX2.BB151354-01C6-43DE-ABCC-0B03468D54FF.pkl

288it [00:21, 13.54it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BL-A5ZZ-01Z-00-DX1.4CF32B22-118E-4570-B341-0F35258329E6.pkl

376it [00:28, 13.18it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A0S7-01Z-00-DX1.32588823-EE4E-4F55-B586-29E8E9D98EDE.pkl

1086it [01:20, 13.42it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A0YX-01Z-00-DX1.B28C49EA-BF1C-44D8-B9A0-DC0A6172702E.pkl

790it [01:01, 12.76it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20J-01Z-00-DX1.EB1BC7DB-9BF1-467D-B897-9BA2130320CB.pkl

471it [00:37, 12.69it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20N-01Z-00-DX1.0FB9D7FF-BDF5-4768-A6F3-D8D16A899772.pkl

702it [00:55, 12.57it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20O-01Z-00-DX1.BD64154E-5CB0-4088-94CC-C48C036E3715.pkl

638it [00:50, 12.71it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20P-01Z-00-DX1.721A7D6B-C9F3-4A70-8E84-EA2556349AE1.pkl

619it [00:48, 12.64it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20Q-01Z-00-DX1.BFF3D35C-CB0C-49C3-8D35-D5C84E133B49.pkl

802it [01:01, 13.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20R-01Z-00-DX1.38320FC0-F1E5-401B-9336-D77796456B30.pkl

581it [00:44, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20T-01Z-00-DX1.96460E53-65E0-425F-B079-939D7AA537BE.pkl

803it [00:58, 13.77it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20U-01Z-00-DX1.C2FDF7E9-3391-44E8-9E84-C5EA8EB4AB4C.pkl

1128it [01:30, 12.51it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A20W-01Z-00-DX1.26F73765-704B-4D81-923D-F20860A3EFFC.pkl

780it [01:01, 12.72it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A2LA-01Z-00-DX1.B76379CE-99AB-4598-B55B-0FA800B8DB74.pkl

690it [00:53, 12.85it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A2LB-01Z-00-DX1.046294E0-4665-41B8-9B95-1A166163EC99.pkl

907it [01:06, 13.71it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A2LD-01Z-00-DX1.A2AEDD2E-481A-401B-BDD7-5D680B5E36E9.pkl

100%|██████████| 674/674 [00:53<00:00, 12.63it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A3PH-01Z-00-DX1.18FB196C-9F66-4676-81DC-F58A0A5577D8.pkl

393it [00:28, 13.58it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A3PJ-01Z-00-DX1.C730AD35-81DF-4758-97B5-1E9F58E67A2B.pkl

790it [01:03, 12.49it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A3PK-01Z-00-DX1.0C10EB75-B766-47DB-8BD0-853F81074355.pkl

951it [01:14, 12.70it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42B-01Z-00-DX1.00FCBDE2-728B-4024-A515-64A366DAB307.pkl

719it [00:58, 12.33it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42C-01Z-00-DX1.49949E15-B218-4E43-947C-5D73B87B1CA9.pkl

522it [00:42, 12.18it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42E-01Z-00-DX1.7DAF02FF-70D0-412D-8EE3-03AC04E83300.pkl

722it [00:56, 12.83it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-BT-A42F-01Z-00-DX1.B934B6A1-C16E-4796-A297-9E92DD74763F.pkl

581it [00:44, 13.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0EZ-01Z-00-DX1.993A12F0-9687-4E56-B887-13C9453A7E63.pkl

520it [00:37, 13.70it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F0-01Z-00-DX1.8EBBC2EF-DA6F-4901-838D-C1AC80E83E92.pkl

698it [00:53, 12.96it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F1-01Z-00-DX1.C29436CC-B584-4898-8168-97B5552B1B24.pkl

1030it [01:16, 13.48it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F6-01Z-00-DX1.05FAB26A-4BE9-42B4-95F0-6BD15EBE8792.pkl

286it [00:21, 13.34it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-C4-A0F7-01Z-00-DX1.606C3AFA-F93D-4226-AA49-41B5916F9018.pkl

369it [00:29, 12.56it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A1HR-01Z-00-DX1.C56E4296-EB85-4DBA-B0A0-9D6FA097A74F.pkl

401it [00:31, 12.58it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A1HS-01Z-00-DX1.CA67D874-12C9-49AB-ACA1-92C202E27083.pkl

408it [00:34, 11.95it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A27C-01Z-00-DX1.0FDBC44E-EC0D-4C6F-8B77-177CB1516CF1.pkl

328it [00:24, 13.47it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MF-01Z-00-DX1.91768C26-5BB1-4DE6-9737-AA26BD687A75.pkl

868it [01:04, 13.48it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MG-01Z-00-DX1.49D55C73-735B-496E-82DA-1F6BFE88D607.pkl

244it [00:18, 13.11it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MH-01Z-00-DX1.4A6F7BDC-B7D2-4203-AA8E-7BA5DB8BF3AC.pkl

461it [00:35, 13.13it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A3MI-01Z-00-DX1.5619CA1A-F772-44CC-BBE2-F2C365E2699D.pkl

721it [00:56, 12.72it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47S-01Z-00-DX1.1397F7C0-1098-4C42-B158-28A37723F5F6.pkl

638it [00:54, 11.75it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47T-01Z-00-DX1.2AFA4BB3-B97C-4C0D-86F4-53A5F3317129.pkl

591it [00:45, 12.87it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47V-01Z-00-DX1.DCDFBB74-48BC-434A-ABD3-55367C56F2FD.pkl

510it [00:40, 12.73it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47W-01Z-00-DX1.D14F1F9A-E684-4140-9714-3197A4325568.pkl

516it [00:37, 13.68it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47X-01Z-00-DX1.1FA2C95C-CFB9-47AA-9BA8-2C2D391BA5D7.pkl

701it [00:51, 13.53it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A47Y-01Z-00-DX1.1D4B8964-E7AB-4C6F-80AC-AF84B80B80C2.pkl

602it [00:44, 13.50it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A5U8-01Z-00-DX1.D0385BD3-3128-41C6-889D-4EC916B2B228.pkl

460it [00:33, 13.60it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A5UA-01Z-00-DX1.7352D4EB-46F5-4EAA-95B9-1D869E8291C3.pkl

416it [00:31, 13.37it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A7I0-01Z-00-DX1.9920A024-B523-4CB6-992F-0BD80D9E11C9.pkl

355it [00:25, 13.88it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A8HX-01Z-00-DX1.92B22756-3D98-4DE6-A077-36C9F1AF1EC2.pkl

272it [00:19, 13.73it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A8HY-01Z-00-DX1.53F599FE-3A6D-4BAC-92B2-CBE3F183BB71.pkl

389it [00:29, 13.40it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FF-01Z-00-DX1.69267287-0015-4BC2-A965-CEE9D0CFC5AA.pkl

218it [00:16, 13.44it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FH-01Z-00-DX1.26AACDC9-1C0B-4AD4-A484-E093515F42B1.pkl

516it [00:37, 13.83it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FL-01Z-00-DX1.711B523B-E033-41ED-AE06-6233C89DCC57.pkl

757it [00:55, 13.57it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CF-A9FM-01Z-00-DX1.F9379708-8E04-435E-BF12-8E3222AE728D.pkl

773it [00:56, 13.58it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A0YN-01Z-00-DX1.6C5EAAAF-8F14-49D3-8FFC-9BDAE56CAFD0.pkl

104it [00:07, 13.86it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A0YO-01Z-00-DX1.847097EC-2E17-44BA-9162-6AA298B7CAFD.pkl

551it [00:41, 13.30it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A0YR-01Z-00-DX1.B3690B2C-0B90-47D6-8709-D493A74E3F7B.pkl

250it [00:19, 12.68it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A3KJ-01Z-00-DX1.5E6E8B80-4059-4625-AED8-D049F4B63FF7.pkl

373it [00:29, 12.47it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A3YL-01Z-00-DX1.813C9F59-869C-4B8E-B295-22F67AD83F37.pkl

666it [00:52, 12.67it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A5W6-01Z-00-DX1.11155086-4A71-4207-85B9-CAF7B6D3D60D.pkl

336it [00:28, 11.93it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-CU-A72E-01Z-00-DX1.11B1B313-85DB-460B-9B78-398224F63A04.pkl

661it [00:50, 13.17it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A3-01Z-00-DX1.89FB6586-56D1-4EF7-AE4B-66EED29667CD.pkl

549it [00:40, 13.45it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A5-01Z-00-DX1.463753DB-C4EA-4973-AF04-4BD0FF39C19D.pkl

714it [00:54, 13.20it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A6-01Z-00-DX1.FC604B50-6BA7-488C-A153-7F9610E6E37B.pkl

799it [01:04, 12.40it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1A7-01Z-00-DX1.57B1442D-8862-447F-98D4-0D52F7B94E62.pkl

518it [00:40, 12.80it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AA-01Z-00-DX1.11F015AE-3B8A-4827-93E2-54F8563BE248.pkl

1005it [01:15, 13.25it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AB-01Z-00-DX1.D6032D7B-43EF-469B-A29D-D6DC41DB46D7.pkl

533it [00:38, 13.84it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AC-01Z-00-DX1.6F484315-00FC-4D41-86E2-16200DC61A04.pkl

1087it [01:28, 12.31it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AD-01Z-00-DX1.1B438E00-C022-4CB8-994D-C4EE8E009F00.pkl

625it [00:46, 13.47it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AE-01Z-00-DX1.85F1B791-E0CD-479F-9C2D-E411981E4471.pkl

623it [00:47, 13.24it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AF-01Z-00-DX1.E18DE029-27A6-43A6-9E9D-D0225C7D5324.pkl

1130it [01:26, 13.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A1AG-01Z-00-DX1.1794B149-3C25-4C51-B96F-1EA24BCBBB3C.pkl

913it [01:06, 13.74it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2HX-01Z-00-DX1.F5D261DF-5A52-4BF6-B892-89B245809F7B.pkl

658it [00:48, 13.61it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I1-01Z-00-DX1.7EBA720C-60F8-4012-95D2-F4B10FB74A18.pkl

338it [00:25, 13.27it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I2-01Z-00-DX1.FF39546E-EE64-4287-8CB5-585801A08519.pkl

835it [01:03, 13.12it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I4-01Z-00-DX1.2DE79A2D-575E-4D5A-A6E3-89D551A5FA46.pkl

469it [00:37, 12.44it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A2I6-01Z-00-DX1.7BF86D3B-D4F7-47F9-B021-7FD6B673A238.pkl

880it [01:10, 12.43it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IK-01Z-00-DX1.2C3A7E93-113C-4321-94B1-7A228E4897F0.pkl

536it [00:43, 12.20it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IL-01Z-00-DX1.B3F0006E-CB53-4475-9576-3411C835B25A.pkl

666it [00:50, 13.21it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IM-01Z-00-DX1.ED1A8B22-566E-4A95-AF6D-7C9E536BE2B7.pkl

1176it [01:31, 12.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IN-01Z-00-DX1.2AB0F8FC-CC41-4277-A8AF-8AE709D98DA0.pkl

588it [00:43, 13.43it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IQ-01Z-00-DX1.D68A6FD8-6E48-4FC1-BAF3-B80D6198EFAE.pkl

764it [00:56, 13.62it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IS-01Z-00-DX1.31CABE32-36D7-4920-BF5A-9C9D8B54320F.pkl

605it [00:44, 13.57it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IT-01Z-00-DX1.819410F8-5E45-484B-8D98-0A3DAB314C6E.pkl

668it [00:50, 13.33it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IU-01Z-00-DX1.A624F891-20E8-48F6-8FAE-D046F30E257C.pkl

1036it [01:23, 12.39it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3IV-01Z-00-DX1.3E7EDFE4-61F6-4EA8-9A29-D70C2785E408.pkl

1119it [01:29, 12.51it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3WW-01Z-00-DX1.4C3751B5-BD3E-4902-A092-B5877B67851F.pkl

100%|██████████| 804/804 [01:00<00:00, 13.37it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3WX-01Z-00-DX1.02E25F1B-4726-4D9E-BBC0-CF42F548F559.pkl

372it [00:27, 13.74it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3WY-01Z-00-DX1.B2B8F28A-A9A4-4C6E-8C7F-3008DF2DE498.pkl

994it [01:16, 13.00it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3X1-01Z-00-DX1.DE470E1B-1DB4-4985-B11D-ECB02A65CA6C.pkl

1091it [01:20, 13.48it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A3X2-01Z-00-DX1.CB507611-E3AE-43A2-B5F8-EEAE59423E2E.pkl

747it [00:53, 13.85it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6AV-01Z-00-DX1.FC632EEE-668B-4757-B2FB-139D869812E0.pkl

100%|██████████| 785/785 [00:59<00:00, 13.28it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6AW-01Z-00-DX1.C2453A8C-8282-443C-9E76-5B6CAD2FE69B.pkl

512it [00:37, 13.54it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B0-01Z-00-DX1.83628045-FDD9-4167-879F-7813FDCA7D97.pkl

727it [00:54, 13.42it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B1-01Z-00-DX1.16F4E625-D690-45CD-B810-9E7F12EF9A90.pkl

853it [01:04, 13.14it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B2-01Z-00-DX1.23D318D9-A05D-49D5-8C0E-BAA71BC2AFFA.pkl

777it [00:58, 13.39it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B5-01Z-00-DX1.A1A01D61-DAA3-4172-8D69-FF0456190967.pkl

845it [01:01, 13.65it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-DK-A6B6-01Z-00-DX1.CD8B2F09-A5BA-4795-92FD-03A7315C3A2D.pkl

597it [00:44, 13.31it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E5-A2PC-01Z-00-DX1.409697C6-097B-4B24-A54B-B52BEC5A0A9B.pkl

642it [00:49, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E5-A4TZ-01Z-00-DX1.08FA5E08-5AF7-461E-8EBC-200BF969E505.pkl

806it [01:04, 12.56it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E5-A4U1-01Z-00-DX1.A088BCB3-86D7-4895-A168-00981B44EF78.pkl

577it [00:45, 12.76it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A3X6-01Z-00-DX1.5566A0E9-E1C3-4F97-8C82-D2FF3FE3FD8D.pkl

305it [00:24, 12.42it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A3Y1-01Z-00-DX1.D3E81A0B-1D20-4916-8872-81D469A1E276.pkl

445it [00:35, 12.45it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A4IJ-01Z-00-DX1.7215592C-D179-4EE8-81F7-B3E32AE0D830.pkl

100%|██████████| 683/683 [00:51<00:00, 13.27it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A4XJ-01Z-00-DX1.70DA8872-34A6-41B7-8D17-2B15C80EF5CF.pkl

482it [00:36, 13.36it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A519-01Z-00-DX1.F197805D-A2DB-4207-91EC-A9AE1FE16C53.pkl

332it [00:23, 13.94it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A541-01Z-00-DX1.8387CEF8-706B-486C-BC07-783EC1016BCC.pkl

786it [00:59, 13.24it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A5KE-01Z-00-DX1.BDCD4071-5EE5-4863-A722-DAA32F3A7FB4.pkl

200it [00:15, 12.76it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A5KF-01Z-00-DX1.61663245-91CA-423F-9639-30B9F7E216C4.pkl

451it [00:34, 13.14it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A677-01Z-00-DX1.D66285D0-F67B-4423-929B-DF34BBC55C80.pkl

327it [00:24, 13.29it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A678-01Z-00-DX1.C589E72B-7214-4EE9-A796-869C2372DD67.pkl

753it [00:55, 13.56it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A6MD-01Z-00-DX1.7E0C04CD-B51E-47F7-B79D-FEEC9B5023FF.pkl

424it [00:30, 13.86it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A6ME-01Z-00-DX1.114098C0-6CD9-4240-B8F4-C2E6D86A6868.pkl

899it [01:12, 12.47it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A6MF-01Z-00-DX1.2B0C8CBF-3244-4D17-B9CA-3CBE000BEC29.pkl

265it [00:19, 13.60it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A7DU-01Z-00-DX1.25C7F59E-1F03-47EF-9F17-DB9ADB16276E.pkl

1020it [01:14, 13.65it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A7DV-01Z-00-DX1.FCE4752B-30BC-4747-A9F4-38141E09F005.pkl

999it [01:13, 13.66it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A7PW-01Z-00-DX1.27B92FC6-D50C-4816-A2C2-35E73D379DDD.pkl

1145it [01:31, 12.48it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A7XN-01Z-00-DX1.5C955881-5B13-4D6B-B99C-E849ADCDE647.pkl

1039it [01:24, 12.34it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A85H-01Z-00-DX1.0C1D94F2-1120-45AC-9053-7833DA12194F.pkl

1279it [01:34, 13.46it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A8O7-01Z-00-DX1.E3D79C43-608D-40A1-9F65-0414FDF27741.pkl

631it [00:47, 13.16it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A8O8-01Z-00-DX1.009173C4-BC8E-4B96-98FC-E24A39438F4E.pkl

559it [00:41, 13.62it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A97P-01Z-00-DX1.09FD969F-62C2-4C79-A826-657A7991C87B.pkl

549it [00:42, 13.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-E7-A97Q-01Z-00-DX1.821AF545-5433-4D2C-AACE-EA206E15B13D.pkl

153it [00:11, 13.56it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B3-01Z-00-DX1.CD634C50-2746-468E-BEEC-50E76E400602.pkl

1088it [01:18, 13.89it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B4-01Z-00-DX1.45B61DCC-09B4-4863-875A-ED1DEECE5F27.pkl

1190it [01:32, 12.87it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B5-01Z-00-DX1.69DEA650-3D53-46AC-BB60-BF68C4413608.pkl

1132it [01:27, 12.96it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B6-01Z-00-DX1.04CCC012-F2FF-4CBA-9A2C-8EC979427204.pkl

905it [01:07, 13.42it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B7-01Z-00-DX1.758419EB-E5A3-4383-817A-B3870FBA1776.pkl

975it [01:12, 13.45it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3B8-01Z-00-DX1.85E75835-8607-47C3-B8BD-4F01E54E5574.pkl

637it [00:51, 12.41it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3N5-01Z-00-DX1.C42537CC-55C9-43CD-921E-75D010B06582.pkl

994it [01:16, 13.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3N6-01Z-00-DX1.C94C21D1-83F2-45EE-A7BE-6A4E5C9B1A89.pkl

978it [01:12, 13.47it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3NA-01Z-00-DX1.2AD62CEE-0D76-4382-AE2E-9B7FCB1130D9.pkl

1115it [01:27, 12.68it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SJ-01Z-00-DX1.CF7DF110-22A8-4071-9717-A71915407248.pkl

1207it [01:30, 13.38it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SL-01Z-00-DX1.7B364C1F-3879-43C1-A3C7-B1CB03A7616B.pkl

1106it [01:21, 13.62it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SM-01Z-00-DX1.D391C864-B5B5-4C4D-915F-FBD8BCACAD36.pkl

1277it [01:37, 13.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SN-01Z-00-DX1.CB50ED59-FB7E-4892-AF72-6D297EC62466.pkl

1030it [01:15, 13.72it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SO-01Z-00-DX1.C3A855BF-976F-4E2B-9E39-3D1AEA1A67F6.pkl

779it [00:58, 13.32it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SP-01Z-00-DX1.05986238-A4B9-497D-9D00-8DB37B0040FE.pkl

726it [00:54, 13.41it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SQ-01Z-00-DX1.86DF2023-BD72-4D84-B7AA-2330AA433DB9.pkl

930it [01:10, 13.13it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SR-01Z-00-DX1.7E2FB51A-9562-4B3D-8431-6283342B4311.pkl

674it [00:52, 12.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A3SS-01Z-00-DX1.FEEC4D8E-E87D-4742-B377-5DA2999D6997.pkl

813it [01:04, 12.51it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43N-01Z-00-DX1.57422C5F-A3A1-4595-9E06-C05C7FF5944B.pkl

1278it [01:32, 13.78it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43P-01Z-00-DX1.792612F7-802C-4A90-A2B5-A6A82FCDE92F.pkl

1073it [01:19, 13.47it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43S-01Z-00-DX1.528CA6F1-B53B-4396-B776-9761B578DCDE.pkl

972it [01:14, 13.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43U-01Z-00-DX1.003EC6EC-229E-4578-BF5B-1FB3EBF68845.pkl

706it [00:54, 13.07it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43X-01Z-00-DX1.CB2A73D9-F64C-4553-8D11-4C25CEF98C45.pkl

1191it [01:33, 12.77it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A43Y-01Z-00-DX1.6516167F-A303-4524-98D6-E32CB521ED08.pkl

661it [00:51, 12.85it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BR-01Z-00-DX1.53CA363B-8DA6-465A-9FEA-2D120B5787A8.pkl

1101it [01:25, 12.85it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BS-01Z-00-DX1.A7155CEB-37C9-4AD2-B229-B76F18814585.pkl

1234it [01:34, 13.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BT-01Z-00-DX1.2A4716E6-A5C0-4C69-82FD-E771ABB3B28D.pkl

879it [01:07, 12.93it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BU-01Z-00-DX1.94A8468C-59E7-4185-A877-CC271EA01C90.pkl

876it [01:07, 13.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BV-01Z-00-DX1.FD47C060-5104-45AC-95F8-0C4C5924FE26.pkl

927it [01:11, 12.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BX-01Z-00-DX1.172B23F4-4651-4C93-93E1-D0E81331DCA7.pkl

100%|██████████| 633/633 [00:48<00:00, 13.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BY-01Z-00-DX1.9DF7C69C-FABA-46DC-9954-A7120C65061F.pkl

641it [00:48, 13.15it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5BZ-01Z-00-DX1.344B1F8F-3B3A-4D42-894E-27C5AE265F42.pkl

823it [01:02, 13.07it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5C0-01Z-00-DX1.D11E8348-04DE-4934-B063-2E3F3AD8D110.pkl

906it [01:10, 12.92it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A5C1-01Z-00-DX1.EAD87C49-A25C-4D37-AF27-E27F7016E065.pkl

967it [01:14, 13.00it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A62N-01Z-00-DX1.204E48B7-51D1-49D7-88F3-4BD33A07146A.pkl

751it [00:57, 13.10it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A62O-01Z-00-DX1.4DD5E512-EF71-498B-8C25-18F42D0E1F1F.pkl

840it [01:04, 13.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A62P-01Z-00-DX1.56B14555-896E-420A-AE8B-4E2D35D87871.pkl

1077it [01:21, 13.28it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A62S-01Z-00-DX1.B35DA29A-6F19-4663-9DB2-AB57DAFC84A7.pkl

1369it [01:44, 13.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TA-01Z-00-DX1.FC156A8A-B71C-46A3-B83F-99DB0FC41FC8.pkl

965it [01:14, 13.04it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TB-01Z-00-DX1.CDCC077C-2DFE-4B04-A0D0-69E1CFE80AC5.pkl

884it [01:07, 13.14it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TC-01Z-00-DX1.AC96EA62-D56E-4565-88E0-EBAEB8087C4F.pkl

866it [01:04, 13.33it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TD-01Z-00-DX1.836B03BC-CD19-437D-A925-9862BB08AB1D.pkl

1003it [01:15, 13.25it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TE-01Z-00-DX1.1CD738A0-1D6D-461B-9322-21F77CC3D167.pkl

1102it [01:24, 13.10it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TF-01Z-00-DX1.15B2C3E0-A0D7-4879-82B1-6C9AB09AF8E2.pkl

1087it [01:20, 13.43it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TG-01Z-00-DX1.C49D520E-3589-4623-9BBE-9676BAC83A8F.pkl

949it [01:12, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TH-01Z-00-DX1.1791761E-876F-4AAB-A0B1-272A37A41E3A.pkl

100%|██████████| 881/881 [01:06<00:00, 13.21it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TI-01Z-00-DX1.A451F82D-983B-4646-BFC6-E40A66F2B9C8.pkl

819it [00:59, 13.67it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FD-A6TK-01Z-00-DX1.B685DA87-72A6-4C38-8AA1-40B6E543383C.pkl

746it [00:54, 13.67it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX2.C4531060-32B7-4472-8B6D-3E4477810B9F.pkl

695it [00:50, 13.68it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX6.28B723F7-1035-4DC2-8DB1-87F08166A9FA.pkl

792it [00:57, 13.79it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX3.6709359F-68F9-4B02-B793-359B83F26372.pkl

363it [00:26, 13.83it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX5.B0ABE3C5-94EC-4650-9698-0D4C57291267.pkl

100%|██████████| 501/501 [00:36<00:00, 13.71it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX1.B36BF723-0E71-4FA9-A915-823634B91EA9.pkl

712it [00:52, 13.53it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z7-01Z-00-DX4.7DDE20DA-894A-4751-A7C0-D5740CB30DD9.pkl

853it [01:01, 13.77it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3Z9-01Z-00-DX1.012EC33E-2BEF-4EDB-81D5-6EAC32D90C87.pkl

902it [01:06, 13.54it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3ZE-01Z-00-DX2.147C2363-55A3-4C02-BAF5-4F1256E30542.pkl

863it [01:02, 13.85it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3ZE-01Z-00-DX1.CD478617-4D80-4F36-8908-8480738367C6.pkl

805it [00:59, 13.56it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A3ZF-01Z-00-DX1.1B5E03AA-51A0-4E2B-A2B3-9652B1FA1D55.pkl

384it [00:27, 13.72it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX4.5917B34B-0752-40A9-B749-FB4B5514229B.pkl

365it [00:28, 12.98it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX5.8F79D0A8-5DE6-4159-AA77-61DACB21E867.pkl

367it [00:26, 13.66it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX2.B09F27BF-6786-4CC7-8471-5A73E048A813.pkl

371it [00:27, 13.71it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX3.23DB58B1-62E3-4B74-AF08-198BD843FA22.pkl

408it [00:28, 14.11it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FJ-A871-01Z-00-DX1.72748A33-5021-4AC6-AEF4-9BDA17233AB3.pkl

386it [00:27, 13.97it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FT-A3EE-01Z-00-DX1.1CA5BFA3-F6F7-45DE-83EC-F328AC4EBE80.pkl

1375it [01:40, 13.75it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-FT-A61P-01Z-00-DX1.39960BA6-ECC6-4EE0-B3ED-F3991E3742F6.pkl

552it [00:39, 13.92it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX4.8E4382A4-71F9-4BC3-89AA-09B4F1B54985.pkl

600it [00:45, 13.06it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX3.6DD4B773-86DE-4D58-A405-3C1B45FD6004.pkl

703it [00:53, 13.10it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX7.F421FDF6-AF52-44C9-8AB2-9E37E1B8C8CC.pkl

655it [00:49, 13.12it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX2.42C4093A-A313-41E6-B2FD-B7928F9B32F9.pkl

862it [01:06, 12.93it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX1.44DA27E7-C499-46A1-A871-DBA4E5BCAA6A.pkl

809it [01:01, 13.18it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX5.94164B15-8070-4F16-B0A5-C9345E00BB83.pkl

848it [01:01, 13.74it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX6.60307899-9A64-4176-8617-BEBEFEF81CEE.pkl

100%|██████████| 498/498 [00:36<00:00, 13.80it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EC-01Z-00-DX8.59E69965-ADB5-4E9D-B455-D766A90EB2AD.pkl

567it [00:40, 14.08it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EF-01Z-00-DX3.04EC2CA4-7CCF-4DB6-829D-9067E7EF07C4.pkl

979it [01:11, 13.73it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EF-01Z-00-DX2.90428613-C414-421F-9502-EADCEBC47184.pkl

745it [00:53, 13.91it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EF-01Z-00-DX1.5FA6C53C-C749-46CE-B85C-DDFE27962F7C.pkl

786it [00:56, 13.85it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EF-01Z-00-DX4.70FC5B2D-E8EC-41EE-99B7-CB3FFC0F4D98.pkl

794it [00:59, 13.30it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX6.6EFFECC5-45F4-4828-8AD7-84E060E6FC9D.pkl

773it [00:58, 13.24it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX7.79C8E05D-5640-49AC-923D-58030F64DD5A.pkl

842it [01:02, 13.41it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX2.3DCD4041-FBE0-45B4-BD5B-6A9E8200289C.pkl

676it [00:49, 13.66it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX1.BBADB2AF-BF32-4678-A54B-F82CA11DC715.pkl

735it [00:55, 13.17it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX8.C3EB2C27-F483-4CE5-AF8D-2AF462AB296F.pkl

722it [00:56, 12.86it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX5.B20A9A5E-23B7-4C19-A021-8B19D56C80B2.pkl

737it [00:56, 12.96it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX4.A156EE54-2814-415F-A7AD-9E408E7B0F50.pkl

536it [00:40, 13.30it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EJ-01Z-00-DX3.3FA3BE61-17DA-4CFE-8845-0889701340EB.pkl

440it [00:31, 13.97it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EK-01Z-00-DX1.1F826341-0877-46E0-8DB7-9D01E8874614.pkl

625it [00:45, 13.65it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EK-01Z-00-DX2.F68EC7A1-2B48-42EB-8621-39D8547E408D.pkl

604it [00:43, 13.82it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EK-01Z-00-DX3.22408270-F6D1-4257-9014-E13C7B69A407.pkl

695it [00:51, 13.50it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EL-01Z-00-DX1.CCC37120-A9F0-4278-9EA6-6CD1A132596C.pkl

827it [01:03, 12.97it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EL-01Z-00-DX2.2E59E1ED-C518-46EC-B60A-B083BA3A77C7.pkl

1124it [01:26, 12.95it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX8.04D3920F-D1FD-4B37-8229-877FC64C3492.pkl

549it [00:39, 14.02it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX4.BE1980E2-83B2-4E04-A6A4-9B71B15793B5.pkl

195it [00:13, 14.08it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX2.94CC403C-1986-4906-AF11-92E349C8A114.pkl

226it [00:16, 14.00it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX6.8FBEA23E-DC4C-4420-A72A-FDDC0CC1F80A.pkl

239it [00:17, 13.69it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX1.E2FEF97D-F947-4497-8605-BBBFC3EC665B.pkl

100%|██████████| 155/155 [00:11<00:00, 13.37it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX7.5784EBED-47AE-4ADA-84F2-3E58965EE2BC.pkl

293it [00:22, 12.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX5.85F4C6CF-E10B-4EF7-B477-D42E9F78247F.pkl

308it [00:23, 13.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2EO-01Z-00-DX3.F64AE021-27AB-4B3C-9DD2-9B8A358326C3.pkl

276it [00:20, 13.25it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX1.B80524C7-9705-461E-852E-DA99575FABF0.pkl

825it [01:03, 12.93it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX4.F8B9CC1E-CDC8-4335-82DD-4BE4F6A35CEF.pkl

599it [00:45, 13.04it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX5.3576FA08-47B1-4A10-94F1-5F5A57A7835E.pkl

714it [00:51, 13.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX3.4127F544-FC83-44F6-85CD-3F1542785E71.pkl

176it [00:12, 14.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX7.03160CC5-FC81-4A8D-96D4-BCEBADCDF599.pkl

385it [00:28, 13.65it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX2.CA66A071-D602-41CD-BD39-4AF1FD7BFC43.pkl

710it [00:55, 12.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A2ES-01Z-00-DX6.FF3254DB-03CE-48A3-8C68-E0BAE60694F6.pkl

599it [00:45, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IB-01Z-00-DX2.233CCEF1-7332-4940-84A6-7CD6ADE8272E.pkl

628it [00:47, 13.18it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IB-01Z-00-DX4.2AECF9F2-3DC4-4474-9D1D-13B40EC9DBDD.pkl

203it [00:14, 13.83it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IB-01Z-00-DX1.27F44B48-11D5-438D-B568-E099C05AD428.pkl

606it [00:45, 13.18it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IB-01Z-00-DX3.87062FFE-72F3-48E0-A9CD-71F5FF3819D3.pkl

758it [00:56, 13.43it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IE-01Z-00-DX1.DEEF9D35-CE4C-499F-9481-9E9E379694FC.pkl

1080it [01:18, 13.82it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3IE-01Z-00-DX2.48A6B225-8608-41A5-9268-63262105DDED.pkl

688it [00:51, 13.39it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-A3VY-01Z-00-DX1.E571536B-7C5A-48DC-9CED-5ACA78DDD43F.pkl

385it [00:27, 14.12it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX3.A193600C-0B83-4FEB-AB0C-DECF6FC78E1A.pkl

212it [00:14, 14.16it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX2.B9AC70CF-591B-4AFF-A8C0-F43A9C91CFF9.pkl

100%|██████████| 537/537 [00:38<00:00, 13.94it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX4.6E70BFE1-D95F-48A9-9897-97322FBA937A.pkl

733it [00:54, 13.37it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX1.F4F8CCF4-E74C-4B07-B385-5E30E0E1BB0D.pkl

486it [00:37, 12.84it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3B-01Z-00-DX5.57084980-934B-4A4A-A720-24FA2E9E0CB2.pkl

583it [00:43, 13.36it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3C-01Z-00-DX2.00AE9115-F979-4DD6-8364-96493CC00835.pkl

1145it [01:22, 13.83it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3C-01Z-00-DX1.D2CA01A1-A2F3-4624-A022-BAEA71AA67AC.pkl

803it [00:59, 13.49it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3D-01Z-00-DX1.8C31FE8D-13F9-49FF-A4FB-2D004B109394.pkl

72it [00:05, 12.13it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX1.C63054C3-6DBF-42A1-ADA3-79FF26ED02B3.pkl

825it [01:01, 13.39it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX4.8DD53108-E08F-4F3C-80EE-E31D934B9BDF.pkl

1039it [01:16, 13.60it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX8.D27EA057-F808-44FE-AF5D-9F7237D59488.pkl

955it [01:10, 13.54it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX3.360ECD0E-F773-4153-A782-EDED1819BDBA.pkl

1017it [01:17, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX9.77E9E77B-0A41-4045-A1EE-19FEC7259910.pkl

823it [01:00, 13.57it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX2.8991BE4B-303B-4177-9046-2D6412D0698E.pkl

1074it [01:16, 13.97it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX6.AD188C41-F5A7-49ED-9C1A-F7E956A34AC5.pkl

931it [01:08, 13.63it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX5.A1D2BBD8-A1B6-46E1-8D22-C897019DB41F.pkl

919it [01:09, 13.25it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-G2-AA3F-01Z-00-DX7.61BFF067-ADE1-4879-8746-34F034B06A2A.pkl

792it [00:58, 13.61it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3BM-01Z-00-DX1.8880FA8C-8607-4C55-A619-2C8D7F2866EF.pkl

93it [00:06, 14.15it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3I6-01Z-00-DX1.47650F7B-0AD3-49C9-AB9E-40383C7D07AC.pkl

108it [00:07, 14.22it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3OO-01Z-00-DX1.F2A671AF-74E6-4F9B-8ABC-6A10EB1F68A8.pkl

261it [00:18, 14.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3RB-01Z-00-DX1.C0011A55-EA8A-436B-BBCA-342B96803B22.pkl

86it [00:06, 13.83it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3RC-01Z-00-DX1.DC4B31BC-5C7F-421A-88CD-38428051A653.pkl

282it [00:20, 13.59it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3RD-01Z-00-DX1.40B5E97D-B45F-4C93-A41B-0F17B757491B.pkl

1108it [01:21, 13.65it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3WC-01Z-00-DX1.D8F5CD43-7338-414C-ADE8-AC0BBC6A871C.pkl

72it [00:05, 13.02it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A3YS-01Z-00-DX1.97B4664A-9D8B-460D-B4A4-89855D3DB0C2.pkl

223it [00:17, 13.06it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A4ZW-01Z-00-DX1.6ECD07FB-AE2C-4A04-812F-F5FB2B31F820.pkl

702it [00:52, 13.42it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A6I1-01Z-00-DX1.2AD569EC-372B-4B72-A222-924091ADEE99.pkl

79it [00:05, 14.17it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GC-A6I3-01Z-00-DX1.1B3D09B9-14FB-4236-9354-3E5CC59354A7.pkl

288it [00:20, 14.18it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A2C5-01Z-00-DX1.3A81505E-5BF9-466C-938B-28909CD88193.pkl

262it [00:18, 14.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A3OP-01Z-00-DX1.A1D66E35-8E4D-4420-AD57-D45016D016D5.pkl

381it [00:27, 13.81it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A3OQ-01Z-00-DX1.ED8C9F09-57A9-4915-950A-A61FE2FE8538.pkl

271it [00:19, 13.94it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A3OS-01Z-00-DX1.5EA796F4-E7F3-4421-BDEA-522BED020B5B.pkl

222it [00:16, 13.85it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A6C6-01Z-00-DX1.5C5F2FA2-6284-4DD8-BE73-D13A88988640.pkl

196it [00:13, 14.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GD-A76B-01Z-00-DX1.C299842E-F204-4071-AD72-1E1A303B396B.pkl

132it [00:09, 14.06it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42P-01Z-00-DX2.3A4A8614-693F-452C-BB2C-AD16D5AC6F12.pkl

920it [01:05, 13.99it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42P-01Z-00-DX1.3A4A8614-693F-452C-BB2C-AD16D5AC6F12.pkl

994it [01:13, 13.61it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42Q-01Z-00-DX2.91D8B0D2-538F-4411-9B3C-0E1FAE1A0606.pkl

436it [00:33, 13.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42Q-01Z-00-DX1.91D8B0D2-538F-4411-9B3C-0E1FAE1A0606.pkl

561it [00:40, 13.89it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42R-01Z-00-DX1.1A14BFD8-DE37-4D10-ACB6-317ECEB930CA.pkl

898it [01:04, 14.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A42R-01Z-00-DX2.B54CCE4D-E4DE-473B-B7C6-5A349FD7F55C.pkl

519it [00:36, 14.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A762-01Z-00-DX1.F01B133E-3744-4430-9752-FDD25EEF58A3.pkl

100%|██████████| 940/940 [01:12<00:00, 13.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A763-01Z-00-DX1.2B511825-320B-48D7-B8D6-D97894C02667.pkl

639it [00:46, 13.82it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A764-01Z-00-DX1.213E1BDD-33DE-454E-BE79-940E5D793D42.pkl

917it [01:05, 13.99it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A766-01Z-00-DX1.72BD6744-E817-4B15-BF58-64BDBC1943FF.pkl

705it [00:50, 14.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-A767-01Z-00-DX1.A8B13490-D25A-45E1-A2D8-02125DB3A6B2.pkl

509it [00:36, 13.78it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-AATO-01Z-00-DX1.1F0F2098-E4DF-4AA3-819E-E0DE23C5A0BE.pkl

676it [00:50, 13.37it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-AATP-01Z-00-DX1.0D8EC37C-88E7-49D5-A76D-F0A4A3FD8AE4.pkl

774it [00:57, 13.50it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GU-AATQ-01Z-00-DX1.6D436809-1238-44CA-9CFC-03DC2277C192.pkl

759it [00:54, 13.83it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3JV-01Z-00-DX1.F071374F-1290-4A36-9466-D6F1F3EBC17E.pkl

678it [00:48, 13.89it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3JW-01Z-00-DX1.152AD6E5-D30A-4D94-A793-3DDF3828625C.pkl

523it [00:38, 13.63it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3JX-01Z-00-DX1.36A00B8A-662D-43EE-AB52-CBBBF373BCFF.pkl

100%|██████████| 639/639 [00:46<00:00, 13.64it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3JZ-01Z-00-DX1.5DFDE227-D52D-481F-A8D8-28DF25096BD9.pkl

757it [00:56, 13.33it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QF-01Z-00-DX1.C59696CF-C415-46AD-B6D6-70A022AC10FA.pkl

785it [00:57, 13.68it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QG-01Z-00-DX1.4A550B20-2A4C-48E5-BFE2-6EBBC59E4041.pkl

958it [01:11, 13.48it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QH-01Z-00-DX1.A87C25E1-8199-4557-944B-9ABD1A70ADE9.pkl

522it [00:40, 12.97it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QI-01Z-00-DX1.0B9889AC-06C7-405F-B300-D93EB0F19D9A.pkl

693it [00:50, 13.71it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A3QK-01Z-00-DX1.DACDDD23-0DD8-44EC-9FE2-945ADEA8AC43.pkl

1062it [01:17, 13.62it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A40E-01Z-00-DX1.6313DD1A-6E65-4775-82DC-58AD4EF81D32.pkl

674it [00:49, 13.63it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A40G-01Z-00-DX1.AD1A709F-A10C-4E69-B4ED-6361777361FD.pkl

713it [00:52, 13.63it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-GV-A6ZA-01Z-00-DX1.6EBD225D-5EE2-4F0A-BC07-1EF5CEBFE25A.pkl

1166it [01:25, 13.59it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-H4-A2HO-01Z-00-DX1.37FB76BF-EA5F-430D-89A4-8789ECACC5DB.pkl

858it [01:03, 13.50it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-H4-A2HQ-01Z-00-DX1.DFBDDFDD-0C65-4130-96F5-4E3838190D13.pkl

604it [00:46, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-HQ-A2OE-01Z-00-DX1.6F764592-DFDC-4636-BE91-3F1F92EE5A65.pkl

100%|██████████| 313/313 [00:22<00:00, 13.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-HQ-A2OF-01Z-00-DX1.6D50B772-71C3-40C3-94CF-969946799028.pkl

304it [00:22, 13.25it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-HQ-A5ND-01Z-00-DX1.EDDFB95C-827E-4533-B49A-56612BC4D9DD.pkl

312it [00:22, 13.68it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-HQ-A5NE-01Z-00-DX1.8046B606-085B-406F-A8D7-92A3E021020A.pkl

133it [00:09, 14.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A3WS-01Z-00-DX1.6814457F-C30E-4B3D-BA37-B701FF591BFE.pkl

100%|██████████| 1211/1211 [01:30<00:00, 13.33it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A3WU-01Z-00-DX1.DD4CA7B4-7950-4B7A-820A-74C763AFAE65.pkl

762it [00:58, 13.04it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A3WV-01Z-00-DX1.F44E3C25-920C-4730-9019-D1E993121F08.pkl

1365it [01:42, 13.33it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A4AB-01Z-00-DX1.88A9D084-1B3B-4B13-AAD7-18C6587624C0.pkl

562it [00:43, 12.92it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A4AC-01Z-00-DX1.DED1674F-953D-40DB-85AE-9CD595248EC7.pkl

1067it [01:21, 13.07it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A54R-01Z-00-DX1.66AAF596-8C68-4857-9944-226F39E82CA8.pkl

405it [00:31, 12.87it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A5RH-01Z-00-DX1.8AA2FC59-CDA4-49F5-BAB7-B14B6792FAF8.pkl

1048it [01:19, 13.24it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A5RI-01Z-00-DX1.A56C3CF4-543E-46D6-BA50-52A4C790FAE8.pkl

1290it [01:37, 13.21it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A5RJ-01Z-00-DX1.DFDDA8B5-E80F-4BF9-87E3-EA75E294ABF5.pkl

798it [01:01, 12.92it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A6FZ-01Z-00-DX1.E4BB7534-1719-45C7-8E0F-78558DB9AD37.pkl

747it [00:56, 13.29it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A6MB-01Z-00-DX1.4A6009D3-05D9-4E8B-8EB2-4A52B5B6FED8.pkl

644it [00:49, 13.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-A83P-01Z-00-DX1.6B9251BD-650E-4F69-BE8F-AB0BE5DC90FB.pkl

790it [00:59, 13.36it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-K4-AAQO-01Z-00-DX1.7533831F-414B-4BA5-9CDA-D8B24E579962.pkl

843it [01:04, 13.04it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-LC-A66R-01Z-00-DX1.9D753031-E31A-4E0E-B937-E0D3C47CFFB9.pkl

585it [00:44, 13.18it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-LT-A5Z6-01Z-00-DX1.F547947F-DDB8-4DFF-B08E-FB494F7F044B.pkl

512it [00:38, 13.15it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-LT-A8JT-01Z-00-DX1.8D04BB53-EEA9-401B-B92E-8EB9DEEE7E4E.pkl

867it [01:05, 13.24it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-MV-A51V-01Z-00-DX1.5D626704-0803-4912-96D5-FB1EEFA509FB.pkl

70it [00:05, 13.13it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-PQ-A6FI-01Z-00-DX1.EC3791D8-B5D2-468A-9FB7-D0217CD02DFB.pkl

644it [00:48, 13.42it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-PQ-A6FN-01Z-00-DX1.58FC60E8-7386-4E57-804D-6AD103AE0FDC.pkl

523it [00:39, 13.32it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-S5-A6DX-01Z-00-DX1.70418D45-0396-4838-BF0C-588C7719A131.pkl

472it [00:35, 13.25it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-S5-AA26-01Z-00-DX1.10D28D0C-D537-485E-A371-E3C60ED66FE7.pkl

481it [00:36, 13.33it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-SY-A9G0-01Z-00-DX1.6F019857-03C8-4B2B-8892-32CBF3EB303F.pkl

183it [00:13, 13.49it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-SY-A9G5-01Z-00-DX1.CE221A12-59FC-4482-9BD5-7082A2EA4E61.pkl

394it [00:29, 13.34it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78K-01Z-00-DX1.329D9BFF-A204-4A7D-8767-B39F34179708.pkl

429it [00:32, 13.36it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78L-01Z-00-DX1.8955EB83-E4AE-452E-8B68-83C4B8BED6D5.pkl

499it [00:36, 13.69it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78M-01Z-00-DX1.9C08E77F-E63B-480E-A4D5-1576EF802152.pkl

602it [00:44, 13.63it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78N-01Z-00-DX1.31873403-A629-4ED9-B2AF-14817689BB3B.pkl

684it [00:51, 13.19it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78O-01Z-00-DX1.6DDC084F-A086-4B5B-90B6-9C45E842A5FA.pkl

808it [01:03, 12.74it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A78P-01Z-00-DX1.B6783816-0322-4453-BC80-20ED79A40588.pkl

1186it [01:29, 13.28it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A8OB-01Z-00-DX1.9DD447FB-44F0-4FFF-8293-9FF0D54A96A0.pkl

1009it [01:14, 13.56it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A8OC-01Z-00-DX1.EE2DF9C6-3CA9-411D-85D4-D1831F14AAFD.pkl

848it [01:02, 13.57it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A8OD-01Z-00-DX1.3985C497-D586-4AB9-A635-63A7946C5A2E.pkl

588it [00:44, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PA-01Z-00-DX1.A83A79FB-810C-42A4-8EC7-A3328D79542D.pkl

1069it [01:22, 12.95it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PB-01Z-00-DX1.4ACBFEEA-703A-47AF-A67D-359B9F027DD0.pkl

675it [00:52, 12.95it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PD-01Z-00-DX1.55AF21E3-74DF-4D18-ADA4-A2A12665DF0A.pkl

765it [00:59, 12.96it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PE-01Z-00-DX1.19205347-9969-475E-9293-E99D4833E462.pkl

747it [00:58, 12.88it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PF-01Z-00-DX1.8A5B3826-48D2-42AE-A4DE-C0BB90134FCB.pkl

589it [00:45, 12.95it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-UY-A9PH-01Z-00-DX1.7FAA1EC7-C2BB-47E0-BCEB-5D4095078B2E.pkl

738it [00:57, 12.93it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HB-01Z-00-DX1.D6874152-D20A-4CA4-8E8B-8CBAB5F7D7B5.pkl

546it [00:40, 13.47it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HC-01Z-00-DX1.BF199254-2954-4836-B037-E10493275D8C.pkl

784it [00:59, 13.15it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HD-01Z-00-DX1.809538C0-0D52-4DA5-AA7D-EDA7B363BF36.pkl

757it [00:57, 13.08it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HE-01Z-00-DX1.A0E05485-2A24-4BD0-8B2F-E0D9641ADD9F.pkl

724it [00:55, 13.02it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HF-01Z-00-DX1.119AB9B9-73CE-4DE3-B305-4872F704E3E4.pkl

996it [01:16, 13.01it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HG-01Z-00-DX1.9D3970D1-C598-4F4C-ABBD-92C55C7C837A.pkl

785it [01:00, 13.06it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HH-01Z-00-DX1.22E9DD6D-F231-422F-A349-9FF60B65D50E.pkl

100%|██████████| 891/891 [01:07<00:00, 13.23it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A8HI-01Z-00-DX1.1BA3EF33-D4D5-4213-833D-A7F8C0EFFF02.pkl

900it [01:09, 12.93it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SG-01Z-00-DX1.6D50B71D-9736-46F9-B527-63565FC65AF2.pkl

366it [00:28, 12.97it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SH-01Z-00-DX1.B1E33049-ABB8-4F2F-9D2D-503E48B8CDE5.pkl

435it [00:32, 13.52it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SI-01Z-00-DX1.537F0394-40FE-4CB7-8524-7BC34F624C15.pkl

786it [00:58, 13.43it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SJ-01Z-00-DX1.AED4FF1B-441D-47EE-B7E5-CC6C595D3D98.pkl

935it [01:12, 12.85it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SK-01Z-00-DX1.1D198106-323F-463B-832B-CB3A03E7B343.pkl

806it [00:59, 13.55it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SL-01Z-00-DX1.AA56A70C-28E1-4140-9B15-72AB0D5051A6.pkl

676it [00:51, 13.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SM-01Z-00-DX1.7AADC753-E07E-44A5-91EC-D1740ED5A168.pkl

655it [00:48, 13.41it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SP-01Z-00-DX1.7F3BF700-89AD-4045-AFCD-C94F1F959B41.pkl

693it [00:52, 13.31it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9ST-01Z-00-DX1.C135C4EB-6A64-4B9E-A8A0-87B72594568C.pkl

354it [00:26, 13.55it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SU-01Z-00-DX1.35E2DDBE-5BB9-443B-A3D5-20F77D1C6B92.pkl

666it [00:51, 12.93it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SV-01Z-00-DX1.2ACAA181-2EFA-4E63-B692-D968BCC56031.pkl

906it [01:10, 12.88it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SW-01Z-00-DX1.3FC62DD6-E5D2-4F74-A937-A2A62946E5C0.pkl

100%|██████████| 589/589 [00:44<00:00, 13.22it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SX-01Z-00-DX1.6DB4572E-915C-491F-BE68-99C019799E20.pkl

661it [00:48, 13.57it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SY-01Z-00-DX1.758C5D9F-274B-4D4A-92D3-78728CB35139.pkl

769it [00:57, 13.35it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9SZ-01Z-00-DX1.42A301F5-42E9-4618-A85A-51C1AEC8B8D1.pkl

893it [01:04, 13.84it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T0-01Z-00-DX1.63C52F23-3DE3-4D3A-914E-E7F3CB23D410.pkl

588it [00:42, 13.91it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T2-01Z-00-DX1.E33F796C-46EB-44C4-AC65-ED6098EE3043.pkl

942it [01:08, 13.67it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T3-01Z-00-DX1.408F9901-F442-420B-BE89-ADBD01D1E256.pkl

777it [00:56, 13.74it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T4-01Z-00-DX1.1F44D95D-E341-4FBA-BCB5-43E89E6C359E.pkl

581it [00:42, 13.59it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T5-01Z-00-DX1.B0A44AF2-B075-4280-809E-DDACCDB20E3D.pkl

588it [00:42, 13.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T6-01Z-00-DX1.57AE17FC-DB4C-4D2B-A53F-A259E8482064.pkl

1214it [01:27, 13.83it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-A9T8-01Z-00-DX1.C18E4176-C0C1-4F5A-B128-23DF5CE77C05.pkl

575it [00:41, 13.81it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAME-01Z-00-DX1.90E1555F-CBAF-434C-9C7E-5BAC38069AC7.pkl

629it [00:44, 13.98it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMF-01Z-00-DX1.01371D44-969E-44C8-993B-13B83D9E4F0F.pkl

327it [00:23, 13.83it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMG-01Z-00-DX1.E0234C99-915C-4190-805A-147D4E3B10D9.pkl

556it [00:40, 13.79it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMH-01Z-00-DX1.AB5E1C7D-C3BF-4A69-B614-0ED69F8A3C07.pkl

749it [00:54, 13.84it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMJ-01Z-00-DX1.726E3D84-8370-45AC-9C98-ACA30CAB2359.pkl

502it [00:36, 13.90it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAML-01Z-00-DX1.E2780FA6-641F-4A5A-B755-9ABD3C57C13E.pkl

1273it [01:32, 13.79it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMQ-01Z-00-DX1.E8D304A9-4BD0-4C62-8B01-4C00994F8EE9.pkl

566it [00:43, 13.00it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMR-01Z-00-DX1.7BFF4F04-9B60-41AA-9977-AF63547748AB.pkl

694it [00:50, 13.78it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMT-01Z-00-DX1.F5A3715A-55DC-46C1-A6F9-4B1BFE1176EC.pkl

1048it [01:18, 13.40it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMW-01Z-00-DX1.875DED6D-805B-418C-8C9E-AE45FDECC504.pkl

799it [01:01, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMX-01Z-00-DX1.453214DD-54FF-42DF-8BD6-E6BC4B376EFF.pkl

655it [00:49, 13.31it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMY-01Z-00-DX1.44D91D18-357D-4FB2-A7CA-38792E3CB839.pkl

746it [00:56, 13.27it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAMZ-01Z-00-DX1.05AB4629-F59E-4877-B7F3-CF4336557EE0.pkl

527it [00:40, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN0-01Z-00-DX1.B9D6C207-F124-4558-ABD4-2846F42C5F66.pkl

642it [00:48, 13.37it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN1-01Z-00-DX1.F6F0E65A-0D01-4C00-AEAC-359D52C802BF.pkl

720it [00:51, 13.96it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN2-01Z-00-DX1.EB523A3A-0DE0-4FFC-9FE7-CF4FB2FB36CF.pkl

518it [00:38, 13.46it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN3-01Z-00-DX1.2F004F0A-57C1-42CA-A07C-CE0FE8F876D5.pkl

597it [00:45, 13.02it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN4-01Z-00-DX1.F9F1800B-9945-4695-B851-A4585E9D56D6.pkl

836it [01:03, 13.08it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN5-01Z-00-DX1.DACB5253-366B-40A2-AD52-376F26C103A6.pkl

622it [00:47, 13.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN7-01Z-00-DX1.B8EDF045-604C-48CB-8E54-A60564CAE2AD.pkl

800it [00:58, 13.66it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-XF-AAN8-01Z-00-DX1.2962EEBB-A4F1-4958-85C9-480B7CA769A8.pkl

464it [00:33, 13.85it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YC-A89H-01Z-00-DX1.ACE5AFD4-274B-4579-9B0E-EDD8D9251A8C.pkl

678it [00:51, 13.25it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YC-A8S6-01Z-00-DX1.6B92FB17-2000-48B0-B7AE-6C8766D958E2.pkl

616it [00:46, 13.35it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YC-A9TC-01Z-00-DX1.D7C1A85C-C39C-436F-A22A-2A09558CCF18.pkl

329it [00:24, 13.38it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YC-A9TC-01Z-00-DX2.F74F61C0-CB9F-4E6E-BDA7-D206ECBBDEFC.pkl

358it [00:27, 13.12it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YF-AA3L-01Z-00-DX1.56C211C1-20C7-4000-9C39-F76919ADA592.pkl

702it [00:53, 13.06it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-YF-AA3M-01Z-00-DX1.28587CDB-1FDF-4FD0-B809-86C7EA64562A.pkl

1470it [01:53, 12.97it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R0-01Z-00-DX1.B9FD30D2-807E-49F7-A9E0-C58226EDEF13.pkl

1025it [01:17, 13.14it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R1-01Z-00-DX1.74520759-D448-45B5-B8AD-45502C99A519.pkl

640it [00:48, 13.17it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R2-01Z-00-DX1.D5BC88BD-594B-4EAA-988E-2577E48FEE15.pkl

948it [01:11, 13.21it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R3-01Z-00-DX1.AF828281-A45C-47D1-9FE3-CE7B9E105914.pkl

100%|██████████| 1020/1020 [01:17<00:00, 13.12it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R4-01Z-00-DX1.0A115B7F-FB7F-4D82-953F-62BF64C1245F.pkl

892it [01:08, 13.12it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R5-01Z-00-DX1.50B18159-9376-411A-B519-12BB50D06DFC.pkl

472it [00:36, 13.05it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R7-01Z-00-DX1.AF323B5F-EE04-422E-B635-1050870897DC.pkl

1055it [01:19, 13.27it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9R9-01Z-00-DX1.8E68A35C-F2B7-410E-A1DE-3C460D67DB85.pkl

725it [00:55, 13.12it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RC-01Z-00-DX1.A3F3826E-2BDE-48C3-9854-1061273AF9DC.pkl

633it [00:47, 13.37it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RD-01Z-00-DX1.84823027-AA0A-412A-9DEA-EFBB8406FD9C.pkl

946it [01:11, 13.16it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RE-01Z-00-DX1.6E1EF772-E62D-4D9F-8688-43AAF764A6E6.pkl

684it [00:52, 13.10it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RF-01Z-00-DX1.948A32F2-EF55-44E8-BC52-6FCF4A3411BF.pkl

1285it [01:35, 13.47it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RG-01Z-00-DX1.E9C92201-31AD-4D7E-87C0-64842D705380.pkl

1088it [01:21, 13.33it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RL-01Z-00-DX1.6A6B23B8-78D2-4468-8B25-A2D94130722C.pkl

378it [00:27, 13.87it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RM-01Z-00-DX1.68758A74-2409-48F4-811A-EA42B4F8F942.pkl

1184it [01:26, 13.69it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-A9RN-01Z-00-DX1.262DCE43-154D-492E-80C3-6F8C8D4058D0.pkl

766it [00:56, 13.66it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4N-01Z-00-DX1.F176510E-CF8B-4681-9CDE-B6210D8DC88F.pkl

877it [01:05, 13.35it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4R-01Z-00-DX1.2CDCECED-FC91-48D4-AAAC-4452B7C2F218.pkl

625it [00:45, 13.68it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4T-01Z-00-DX1.3AC48F6E-01E2-4C20-BEFE-3B4A150DFF67.pkl

306it [00:23, 12.94it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4U-01Z-00-DX1.E7FBFD1C-E974-4B9C-8DA8-D14FEC22D117.pkl

669it [00:49, 13.56it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4V-01Z-00-DX1.04E4C701-9AA4-41DC-A615-4EB695CE8E3C.pkl

589it [00:45, 13.03it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4W-01Z-00-DX1.1B35CC2D-3115-4BCF-8BAD-164806CAA7D3.pkl

577it [00:43, 13.25it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA4X-01Z-00-DX1.925D02DA-FAFF-4F2B-A3CE-BF884E5C4C03.pkl

787it [01:00, 13.09it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA51-01Z-00-DX1.128C9731-C206-4E71-9A64-864FA9FD7E96.pkl

730it [00:55, 13.22it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA52-01Z-00-DX1.BABC9074-8AF5-42E7-B3F8-39590121B620.pkl

1007it [01:16, 13.10it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA53-01Z-00-DX1.04E05AAC-DAE2-428F-98DD-37F2B414E818.pkl

1445it [01:49, 13.21it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA54-01Z-00-DX1.9118BB51-333A-4257-A797-75620F1E7AD6.pkl

921it [01:08, 13.50it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA58-01Z-00-DX1.85C3611E-11FA-4AAE-B880-C67C8CC7383B.pkl

1025it [01:18, 13.00it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA5H-01Z-00-DX1.2B5DF00E-E0FD-4C58-A82C-3107A27F99D6.pkl

853it [01:04, 13.29it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA5N-01Z-00-DX1.A207E3EE-CC7D-4267-A77E-71BBD15B95A8.pkl

903it [01:08, 13.18it/s]

/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/Data/BLCA_WSI/patches_1_224_downsampled/TCGA-ZF-AA5P-01Z-00-DX1.B91697A2-A186-4E67-A818-56271D2009A9.pkl

1126it [01:26, 13.06it/s]

### Update WSI info

In [7]:
WSI_info['embeddings'][1]

'/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/notebooks/WSI/Ji-Qing/cnn_embeddings/TCGA-2F-A9KP-01Z-00-DX1.3CDF534E-958F-4467-AA7E-FD3C5A86AAAA.pkl'

In [8]:
WSI_info['embeddings'] = WSI_info['embeddings'].str.replace('/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/TristanD/notebooks/WSI/Ji-Qing/cnn_embeddings','/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/JiQing/TCGA_model/WSI/Graph_Generating/cnn_embeddings')
WSI_info

,bcr_patient_barcode,age_at_diagnosis,cigarettes_per_day,primary_diagnosis,tissue_or_organ_of_origin,ajcc_pathologic_stage,race,gender,prior_malignancy,vital_status,ajcc_pathologic_t,ajcc_pathologic_n,ajcc_pathologic_m,survival_time,patches_npy,patches_pkl,embeddings,graphs
0,TCGA-2F-A9KO,63.898630,3.780822,Transitional cell carcinoma,Posterior wall of bladder,Stage IV,white,male,no,1,T3,N1,M0,734.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
1,TCGA-2F-A9KP,66.926027,3.397260,Transitional cell carcinoma,Lateral wall of bladder,Stage IV,white,male,no,1,T3a,N2,MX,364.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
2,TCGA-2F-A9KP,66.926027,3.397260,Transitional cell carcinoma,Lateral wall of bladder,Stage IV,white,male,no,1,T3a,N2,MX,364.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
3,TCGA-2F-A9KQ,69.202740,0.000000,Transitional cell carcinoma,"Bladder, NOS",Stage III,white,male,no,0,T3a,N0,M0,2886.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
4,TCGA-2F-A9KR,59.857534,1.232877,Papillary transitional cell carcinoma,"Bladder, NOS",Stage III,not reported,female,no,1,T3a,N0,M0,3183.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,TCGA-ZF-AA54,71.583562,0.000000,Transitional cell carcinoma,Lateral wall of bladder,Stage III,white,male,no,1,T3,NX,MX,590.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
452,TCGA-ZF-AA58,61.778082,2.136986,Transitional cell carcinoma,"Bladder, NOS",Stage IV,white,female,no,0,T3a,N2,MX,1649.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
453,TCGA-ZF-AA5H,60.608219,0.438356,Transitional cell carcinoma,"Bladder, NOS",Stage IV,white,female,no,0,T3b,N2,M0,897.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
454,TCGA-ZF-AA5N,62.304110,0.547945,Transitional cell carcinoma,"Bladder, NOS",Stage IV,white,female,no,1,T2,NX,M1,168.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
455,TCGA-ZF-AA5P,65.673973,3.397260,Transitional cell carcinoma,Posterior wall of bladder,Stage IV,white,male,no,0,T2b,N2,M0,372.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...

In [10]:
WSI_info.to_csv("/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/JiQing/TCGA_model/WSI/wsi_metadata_with_patches_and_embeddings_and_graphs.csv")

In [11]:
WSI_info = pandas.read_csv("/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/JiQing/TCGA_model/WSI/wsi_metadata_with_patches_and_embeddings_and_graphs.csv",index_col=0)
WSI_info

,bcr_patient_barcode,age_at_diagnosis,cigarettes_per_day,primary_diagnosis,tissue_or_organ_of_origin,ajcc_pathologic_stage,race,gender,prior_malignancy,vital_status,ajcc_pathologic_t,ajcc_pathologic_n,ajcc_pathologic_m,survival_time,patches_npy,patches_pkl,embeddings,graphs
0,TCGA-2F-A9KO,63.898630,3.780822,Transitional cell carcinoma,Posterior wall of bladder,Stage IV,white,male,no,1,T3,N1,M0,734.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
1,TCGA-2F-A9KP,66.926027,3.397260,Transitional cell carcinoma,Lateral wall of bladder,Stage IV,white,male,no,1,T3a,N2,MX,364.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
2,TCGA-2F-A9KP,66.926027,3.397260,Transitional cell carcinoma,Lateral wall of bladder,Stage IV,white,male,no,1,T3a,N2,MX,364.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
3,TCGA-2F-A9KQ,69.202740,0.000000,Transitional cell carcinoma,"Bladder, NOS",Stage III,white,male,no,0,T3a,N0,M0,2886.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
4,TCGA-2F-A9KR,59.857534,1.232877,Papillary transitional cell carcinoma,"Bladder, NOS",Stage III,not reported,female,no,1,T3a,N0,M0,3183.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,TCGA-ZF-AA54,71.583562,0.000000,Transitional cell carcinoma,Lateral wall of bladder,Stage III,white,male,no,1,T3,NX,MX,590.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
452,TCGA-ZF-AA58,61.778082,2.136986,Transitional cell carcinoma,"Bladder, NOS",Stage IV,white,female,no,0,T3a,N2,MX,1649.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
453,TCGA-ZF-AA5H,60.608219,0.438356,Transitional cell carcinoma,"Bladder, NOS",Stage IV,white,female,no,0,T3b,N2,M0,897.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
454,TCGA-ZF-AA5N,62.304110,0.547945,Transitional cell carcinoma,"Bladder, NOS",Stage IV,white,female,no,1,T2,NX,M1,168.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...
455,TCGA-ZF-AA5P,65.673973,3.397260,Transitional cell carcinoma,Posterior wall of bladder,Stage IV,white,male,no,0,T2b,N2,M0,372.0,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...,/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Inte...

In [12]:
WSI_info['embeddings'][1]

'/dartfs/rc/nosnapshots/V/VaickusL-nb/EDIT_Interns_2023/user/JiQing/TCGA_model/WSI/Graph_Generating/cnn_embeddings/TCGA-2F-A9KP-01Z-00-DX1.3CDF534E-958F-4467-AA7E-FD3C5A86AAAA.pkl'